### ISSUE TITLE
On DualToR Active-Active testbed, 8 failures in test_tor_ecn.py due to packets not being received on expected port

### ISSUE THREAD

**Issue by AnantKishorSharma** [sonic-net/sonic-mgmt#10078]
**Description**
While running test_tor_ecn.py, after configuration on the duts, 14 out of 16 testcases are failing.

First part of the issue is related to handling the code flow for test cases in test_tor_ecn.py if SYSTEM_DEFAULTS config is not present

Second part of the issue is related to test_dscp_to_queue_during_encap_on_standby and test_ecn_during_encap_on_standby, when these 2 cases are run in A-A/mixed topology, while randomly selecting PTF IP to test we sometimes select IP mapped to a port with active-active config.. If we select such PTF IP, we won't see expected behavior. With this PR we have added a check to select PTF IP mapped to active-standby port.

Issue first part signature:
```
cisco@m64-tor-0-yy41:~$ sonic-cfggen -d -v 'SYSTEM_DEFAULTS.tunnel_qos_remap.status'
 Traceback (most recent call last):
 File "/usr/local/bin/sonic-cfggen", line 443, in <module>
 main()
 File "/usr/local/bin/sonic-cfggen", line 416, in main
 print(template.render(data))
 File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1301, in render
 self.environment.handle_exception()
 File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 936, in handle_exception
 raise rewrite_traceback_stack(source=source)
 File "<template>", line 1, in top-level template code
 File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 485, in getattr
 return getattr(obj, attribute)
 jinja2.exceptions.UndefinedError: 'SYSTEM_DEFAULTS' is undefined

This makes the script fail at [https://github.com/sonic-net/sonic-mgmt/blob/202205/tests/dualtor/test_tor_ecn.py#L101] and outer_dscp is not defined in the script.
```
Issue second part signature:
```
AssertionError: Did not receive expected packet on any of ports [58, 59, 62, 63, 66, 67, 70, 71] for device 0.
```

**Steps to reproduce the issue:**
1. run "test_tor_ecn.py" on dualtor active-active testbeds based on 202205 mgmt

**Analysis:**
First part of the issue can e fixed with tweaking the code to handle the scenario when SYSTEM_DEFAULTS config is not present
Second part of the issue can be fixed by checking if the port selected randomly to test is in A-S state or forcefully changing it so. 

**Describe the results you received:**
14/16 testcases failed

**Describe the results you expected:**
Test cases should pass

    **Output of `show version`:**

    ```
cisco@m64-tor-0-yy41:~$ show ver

SONiC Software Version: SONiC.azure_cisco_202205.6243-dirty-20230828.155612
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: f29e54cb7
Build date: Tue Aug 29 01:42:03 UTC 2023
Built by: sonicci@sonic-ci-19-lnx

Platform: x86_64-8102_64h_o-r0
HwSKU: Cisco-8102-C64
ASIC: cisco-8000
ASIC Count: 1
Serial Number: FLM26300C2M
Model Number: 8102-64H-O
Hardware Revision: 1.0
Uptime: 03:51:17 up 4 days,  2:13,  1 user,  load average: 1.56, 1.57, 1.71
Date: Wed 20 Sep 2023 03:51:17
    ```

**Comment by AnantKishorSharma** [comment]
@bpar9 @lolyu - Closing this issue as the fix is merged to master/active branches.
