### ISSUE TITLE
[voq][chassis] decap/fib tests fail with error in pipeline run

### ISSUE THREAD

**Issue by judyjoseph** [sonic-net/sonic-mgmt#10194]
**Description**

 Tests decap/fib fail with error in pipeline run for voq chassis in 202205

```
2023-09-18T15:23:19.4500504Z decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable] 
2023-09-18T15:23:19.4502816Z -------------------------------- live log setup --------------------------------
2023-09-18T15:23:19.4504260Z 15:23:19 __init__._fixture_func_decorator         L0073 ERROR  | 
2023-09-18T15:23:19.4505229Z KeyError(u'20.0.0.1',)
2023-09-18T15:23:19.4506059Z Traceback (most recent call last):
2023-09-18T15:23:19.4510683Z   File "/azp/_work/8/s/tests/common/plugins/log_section_start/__init__.py", line 71, in _fixture_func_decorator
2023-09-18T15:23:19.4512014Z     return fixture_func(*args, **kargs)
2023-09-18T15:23:19.4513036Z   File "/azp/_work/8/s/tests/common/fixtures/fib_utils.py", line 300, in fib_info_files
2023-09-18T15:23:19.4514177Z     fib_info = get_t2_fib_info(duthosts, duts_config_facts, duts_minigraph_facts)
2023-09-18T15:23:19.4515461Z   File "/azp/_work/8/s/tests/common/fixtures/fib_utils.py", line 107, in get_t2_fib_info
2023-09-18T15:23:19.4516534Z     remote_duthost_name = sys_neigh[neigh_ip]['duthost_name']
2023-09-18T15:23:19.4517873Z KeyError: u'20.0.0.1'
2023-09-18T15:23:19.5371182Z ERROR                                                                    [ 25%]
2023-09-18T15:23:19.5386458Z decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=set_unset] SKIPPED [ 50%]
2023-09-18T15:23:19.5402139Z decap/test_decap.py::test_decap[ttl=pipe, dscp=pipe, vxlan=disable] SKIPPED [ 75%]
2023-09-18T15:24:03.8712371Z decap/test_decap.py::test_decap[ttl=pipe, dscp=pipe, vxlan=set_unset] SKIPPED [100%]
```

The issue is root caused to route entry not getting cleaned up correctly when doing a config load_minigraph during earlier test  bgp/test_traffic_shift.py::test_load_minigraph_with_traffic_shift_away

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by judyjoseph** [comment]
show get resolved with https://github.com/sonic-net/sonic-buildimage/pull/16454
