### ISSUE TITLE
[voq, chassis] test_snmp_loopback fails with assert error 

### ISSUE THREAD

**Issue by judyjoseph** [sonic-net/sonic-mgmt#10344]
**Description**
test_snmp_loopback fails with assert error 

**Steps to reproduce the issue:**
1. Run snmp/test_snmp_loopback.py::test_snmp_loopback on a chassis linecard
2.
3.

**Describe the results you received:**
```
2023-10-01T22:00:46.0406314Z snmp/test_snmp_loopback.py::test_snmp_loopback[svcstr-xxxx-lc1-1] 
2023-10-01T22:00:46.0408428Z -------------------------------- live log call ---------------------------------
2023-10-01T22:00:46.0409733Z 22:00:46 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
2023-10-01T22:00:46.0421788Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
2023-10-01T22:00:46.0422798Z     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
2023-10-01T22:00:46.0424089Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
2023-10-01T22:00:46.0425271Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2023-10-01T22:00:46.0426540Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
2023-10-01T22:00:46.0427356Z     return self._inner_hookexec(hook, methods, kwargs)
2023-10-01T22:00:46.0428195Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
2023-10-01T22:00:46.0428925Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2023-10-01T22:00:46.0429859Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
2023-10-01T22:00:46.0430561Z     return outcome.get_result()
2023-10-01T22:00:46.0431347Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
2023-10-01T22:00:46.0432030Z     _reraise(*ex)  # noqa
2023-10-01T22:00:46.0432824Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
2023-10-01T22:00:46.0433526Z     res = hook_impl.function(*args)
2023-10-01T22:00:46.0434341Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
2023-10-01T22:00:46.0435046Z     testfunction(**testargs)
2023-10-01T22:00:46.0435747Z   File "/azp/_work/8/s/tests/snmp/test_snmp_loopback.py", line 36, in test_snmp_loopback
2023-10-01T22:00:46.0436487Z     "Sysdescr not found in SNMP result from IP {}".format(ip)
2023-10-01T22:00:46.0437344Z AssertionError: Sysdescr not found in SNMP result from IP FC00:10::1/128
2023-10-01T22:00:46.0437656Z 
```

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by judyjoseph** [comment]
@kevinskwang, @mannytaheri had the following observation on this change -- where in the above test failure in snmp is due to this activity in qos where we disable and enable ipv6 vis systemctl.

```

There are no issues when we run SNMP suite by itself and all testcases pass. 
However, test_snmp_loopback test case fails when we run SNMP suite along with other OC suites.
QOS suite runs before SNMP and a combinations of disabling/enabling ipv6 and config reload in QoS leaves the Dut in a bad state.

Qos disables ipv6 (sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1).  This cause ipv6 address of docker0 to be removed.
QoS then enables ipv6 (sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0).  Still no ipv6 address on docker0
Then it does a config reload on the dut.  This causes the ipv6 rules to be removed from ip6tables  (display the ip6tables with “sudo ip netns exec asic1 ip6tables  -t nat  -L -n”)
snmpget fails since there is no ipv6 address on docker0 and the ipv6 rules are removed.

```

Instead of disable enable ipv6, can we shut/unshut the interface ?
