### ISSUE TITLE
Failed to connect to the host via ssh: libvirt: XML-RPC error

### ISSUE THREAD

**Issue by deba-arista** [sonic-net/sonic-mgmt#10404]
TASK [vm_set : Retrieve a list of the defined VMs] **************************************************************************************
task path: /var/AzDevOps/sonic-mgmt/ansible/roles/vm_set/tasks/main.yml:214
Friday 20 October 2023  08:39:23 +0000 (0:00:00.055)       0:00:32.095 ********
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/misc/virt.py
Pipelining is enabled.
<172.30.125.48> ESTABLISH SSH CONNECTION FOR USER: sonic
<172.30.125.48> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="sonic"' -o ConnectTimeout=30 -o ControlPath=/var/AzDevOps/.ansible/cp/96fca49553 172.30.125.48 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=wpgyvlkeyjmrrqlhbwzuovlawnqbtjvm] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-wpgyvlkeyjmrrqlhbwzuovlawnqbtjvm ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<172.30.125.48> (1, '\n{"msg": "Failed to connect socket to \'/var/run/libvirt/libvirt-sock\': No such file or directory", "exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_virt_payload_6h7f717m/__main__.py\\", line 593, in main\\n    rc, result = core(module)\\n  File \\"/tmp/ansible_virt_payload_6h7f717m/__main__.py\\", line 565, in core\\n    res = getattr(v, command)()\\n  File \\"/tmp/ansible_virt_payload_6h7f717m/__main__.py\\", line 346, in list_vms\\n    self.conn = self.__get_conn()\\n  File \\"/tmp/ansible_virt_payload_6h7f717m/__main__.py\\", line 294, in __get_conn\\n    self.conn = LibvirtConnection(self.uri, self.module)\\n  File \\"/tmp/ansible_virt_payload_6h7f717m/__main__.py\\", line 186, in __init__\\n    conn = libvirt.open(uri)\\n  File \\"/usr/lib/python3/dist-packages/libvirt.py\\", line 277, in open\\n    if ret is None:raise libvirtError(\'virConnectOpen() failed\')\\nlibvirt.libvirtError: Failed to connect socket to \'/var/run/libvirt/libvirt-sock\': No such file or directory\\n", "failed": true, "invocation": {"module_args": {"uri": "qemu:///system", "command": "list_vms", "name": null, "state": null, "autostart": null, "xml": null}}}\n', "libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory\n<stdin>:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n")
<172.30.125.48> Failed to connect to the host via ssh: libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
<stdin>:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_virt_payload_6h7f717m/__main__.py", line 593, in main
    rc, result = core(module)
  File "/tmp/ansible_virt_payload_6h7f717m/__main__.py", line 565, in core
    res = getattr(v, command)()
  File "/tmp/ansible_virt_payload_6h7f717m/__main__.py", line 346, in list_vms
    self.conn = self.__get_conn()
  File "/tmp/ansible_virt_payload_6h7f717m/__main__.py", line 294, in __get_conn
    self.conn = LibvirtConnection(self.uri, self.module)
  File "/tmp/ansible_virt_payload_6h7f717m/__main__.py", line 186, in __init__
    conn = libvirt.open(uri)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 277, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

fatal: [STR-ACS-SERV-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "autostart": null,
            "command": "list_vms",
            "name": null,
            "state": null,
            "uri": "qemu:///system",
            "xml": null
        }
    },
    "msg": "Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory"
}

PLAY RECAP ******************************************************************************************************************************
STR-ACS-SERV-01            : ok=38   changed=2    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0

**Comment by deba-arista** [comment]
task path: /var/AzDevOps/sonic-mgmt/ansible/roles/vm_set/tasks/main.yml:214
- name: Retrieve a list of the defined VMs
  virt: command=list_vms
        uri=qemu:///system
  register: vm_list_defined
  become: true
