### ISSUE TITLE
Testcase test_route_flow_counter.py skip fixture would cause error in some platforms

### ISSUE THREAD

**Issue by xwjiang-ms** [sonic-net/sonic-mgmt#10418]
**Description**

When running `test_route_flow_counter.py` script on some platforms, although we need to skip this case, but could also cause error.
The reason is: some platforms do not support "counterpoll flowcnt-route" command, and would return error after executing

------------------------------ live log teardown -------------------------------
04:30:39 __init__._fixture_generator_decorator    L0099 ERROR  | 
run module command failed, Ansible Results =>
{"changed": true, "cmd": ["counterpoll", "flowcnt-route", "disable"], "delta": "0:00:00.428159", "end": "2023-10-17 04:30:39.835946", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-10-17 04:30:39.407787", "stderr": "", "stderr_lines": [], "stdout": "Route flow counter is not supported on this platform", "stdout_lines": ["Route flow counter is not supported on this platform"]}
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_xxxx/tests/common/plugins/log_section_start/__init__.py", line 95, in _fixture_generator_decorator
    next(it)
  File "/var/src/sonic-mgmt/tests/route/test_route_flow_counter.py", line 56, in clear_route_flow_counter
    flow_counter_utils.set_route_flow_counter_status(rand_selected_dut, False)
  File "/var/src/sonic-mgmt/tests/flow_counter/flow_counter_utils.py", line 165, in set_route_flow_counter_status
    dut.command('counterpoll flowcnt-route {}'.format('enable' if status else 'disable'))
  File "/var/src/sonic-mgmt/tests/common/devices/multi_asic.py", line 118, in _run_on_asics
    return getattr(self.sonichost, self.multi_asic_attr)(*module_args, **complex_args)
  File "/var/src/sonic-mgmt/tests/common/devices/base.py", line 127, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module command failed, Ansible Results =>
{"changed": true, "cmd": ["counterpoll", "flowcnt-route", "disable"], "delta": "0:00:00.428159", "end": "2023-10-17 04:30:39.835946", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-10-17 04:30:39.407787", "stderr": "", "stderr_lines": [], "stdout": "Route flow counter is not supported on this platform", "stdout_lines": ["Route flow counter is not supported on this platform"]}

route/test_route_flow_counter.py::TestRouteCounter::test_update_route_pattern ERROR [ 33%]
route/test_route_flow_counter.py::TestRouteCounter::test_update_route_pattern SKIPPED [ 66%]

**Describe the results you received:**
Skip testcase with error

**Describe the results you expected:**
Would skip testcase without error

**Comment by xwjiang-ms** [comment]
@bingwang-ms Could you help to find someone to take a look?

**Comment by bingwang-ms** [comment]
@roy-sror Can you please help take a look? Thanks
