### ISSUE TITLE
SnappiIxnException: IxNet - An error occurred while performing Dod!

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-mgmt#10726]
I am trying to understand what this error means. If anyone can help, pls do so:

Script: tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py

SnappiIxnException: IxNet - An error occurred while performing Dod! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!

Full traceback:13/11/2023 20:31:00 bgp_convergence_helper.get_RIB_IN_capaci L0941 INFO   | IxNet - An error occurred while performing Dod! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!
13/11/2023 20:31:00 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py", line 67, in test_RIB_IN_capacity
    port_speed,)
  File "/data/tests/snappi_tests/bgp/files/bgp_convergence_helper.py", line 206, in run_RIB_IN_capacity_test
    port_speed,)
  File "/data/tests/snappi_tests/bgp/files/bgp_convergence_helper.py", line 887, in get_RIB_IN_capacity
    run_traffic(j)
  File "/data/tests/snappi_tests/bgp/files/bgp_convergence_helper.py", line 881, in run_traffic
    cvg_api.set_state(cs)
  File "/usr/local/lib/python2.7/dist-packages/snappi_ixnetwork/snappi_convergence_api.py", line 139, in set_state
    return self._request_detail()
  File "/usr/local/lib/python2.7/dist-packages/snappi_ixnetwork/snappi_convergence_api.py", line 204, in _request_detail
    raise SnappiIxnException(500, errors)
SnappiIxnException: IxNet - An error occurred while performing Dod! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!IxNet - An error occrred while stopping traffic! Please check the logs for more details!

**Comment by rraghav-cisco** [comment]
@aganguly-keysight @nirmalya-keysight : Any suggestions?

**Comment by kamalsahu0001** [comment]
Hi @rraghav-cisco .. It means that port might have crashed due to Out of Memory while trying to increase the number of routes. Can you please collect the diagnostics and attach it here?

**Comment by rraghav-cisco** [comment]
@kamalsahu0001 : Thanks for responding. I will attempt to recreate the issue. I think it went away after clearing out all the previously left out ixia-API sessions.

**Comment by rraghav-cisco** [comment]
@kamalsahu0001 : I can't upload the diagnostic file to github since it has a upper limit of 25 MB. The diagnostic is 249 
![Uploading Screenshot 2023-11-19 at 9.51.24 PM.png…]()
MB.
