### ISSUE TITLE
[bgp/test_bgpmon.py] - Fails due to Assertion Error in T1 Topology

### ISSUE THREAD

**Issue by mithun2498** [sonic-net/sonic-mgmt#10839]
**Description**

The test case bgp/test_bgpmon.py fails due to Assertion Error in T1 Topology.

**Steps to reproduce the issue:**
1. Deploy T1 topology on a physical testbed.
2. Run bgp/test_bgpmon.py test case.
3.

**Describe the results you received:**
Assertion Error: Did not receive expected packet on any of ports [] for device 0.

**Describe the results you expected:**
Expecting the case to PASS

**Additional information you deem important:**
SONiC Version: SONiC-OS-202305.366435-a49860cc7

**Error Log:**
bgp/test_bgpmon.py::test_bgpmon[dev-msn2700-01-None]
-------------------------------- live log call ---------------------------------
02:47:06 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/sonic-mgmt/tests/bgp/test_bgpmon.py", line 158, in test_bgpmon
    ports=peer_ports, timeout=BGP_CONNECT_TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 2538, in verify_packet_any_port
    % (ports, device_number, result.format()))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Did not receive expected packet on any of ports [] for device 0.

msg        = 'Did not receive expected packet on any of ports [] for device 0.\n========== EXPECTED ==========\nMask:\n0000  00 01 ...31  "#$%&\'()*+,-./01\n0070  32 33 34 35 36 37                                234567\n==============================\n'
self       = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>

/usr/lib/python2.7/unittest/case.py:410: AssertionError
- generated xml file: /data/sonic-mgmt/tests/logs/21-11-2023/test_bgpmon/tr.xml -
=========================== short test summary info ============================
FAILED bgp/test_bgpmon.py::test_bgpmon[dev-msn2700-01-None] - AssertionError:...
===================== 1 failed, 1 passed in 494.28 seconds =====================

**Comment by mithun2498** [comment]
Hi @yxieca @wangxin ,

Kindly help us on this! The issue seen is "AssertionError: Did not receive expected packet on any of ports [] for device 0."

**Comment by yxieca** [comment]
@mithun2498 can you upload the show tech support dump?

Can you confirm that your testbed has passed following tests:

link_flap
fdb
fib
lag

**Comment by mithun2498** [comment]
Hi @yxieca 

Lag cases has passed, but I have 3 failures in fdb out of 8 cases. Earlier all 8 were passing.
I haven't run fib TC.

**Comment by lipxu** [comment]
Hi, @mithun2498 , I checked our nightly builds, and the result of this case should be good, Could you please help to share the latest update, if the failure is persistent from your side, may you please help to upload the full failure log and show tech support, thanks a lot.
