### ISSUE TITLE
Concatenation issue in tests/common/helpers/pfc_gen_t2.py

### ISSUE THREAD

**Issue by harsgoll** [sonic-net/sonic-mgmt#11035]
While running PFCWD test cases, encountered concatenation issue on sonic fanout.

root@xx37-root-fanout:/tmp# sudo nice --20 python pfc_gen_t2.py -p 16 -t 65535 -s 8 -n 1000000 -i Ethernet152 -r 1.76.0.62
Traceback (most recent call last):
  File "/tmp/pfc_gen_t2.py", line 340, in <module>
    main()
  File "/tmp/pfc_gen_t2.py", line 264, in main
    fo_logger.debug(fo_str + ' sendmmsg got errno ' + str(errno) + ' for socket ' + s.getsockname())
TypeError: can only concatenate str (not "tuple") to str

We converted s.getsockname() into str and able to proceed further.

Cc: [sanjair-git](https://github.com/sanjair-git)

**Comment by harsgoll** [comment]
Raised PR https://github.com/sonic-net/sonic-mgmt/pull/11037 to fix this
