### ISSUE TITLE
route/test_route_flap.py failed because of AnsibleConnectionFailure: Host unreachable

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#11353]
**Description**
We encountered the following error when running `route/test_route_flap.py` on VOQ chassis with T2 topo.

```
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/tests/route/test_route_flap.py", line 301, in test_route_flap
    filtered_iproute_info = get_filtered_iproute_info(duthost, route_prefix_len)
  File "/data/tests/route/test_route_flap.py", line 184, in get_filtered_iproute_info
    output = json.loads(duthost.shell('vtysh -c "show ip bgp ipv4 json"', verbose=False)['stdout'])
  File "/data/tests/common/devices/multi_asic.py", line 122, in _run_on_asics
    return getattr(self.sonichost, self.multi_asic_attr)(*module_args, **complex_args)
  File "/data/tests/common/devices/base.py", line 78, in _run
    res = self.module(*module_args, **complex_args)[self.hostname]
  File "/usr/local/lib/python2.7/dist-packages/pytest_ansible/module_dispatcher/v28.py", line 159, in _run
    raise AnsibleConnectionFailure("Host unreachable", dark=cb.unreachable, contacted=cb.contacted)
AnsibleConnectionFailure: Host unreachable
```

According to test log,  test was stuck when dumping ipv4 route from bgp for almost one hour (note the timestamps in the log):

```
18/01/2024 19:13:23 __init__._log_sep_line                   L0170 INFO   | ==================== route/test_route_flap.py::test_route_flap[cmp227-6-None] call ====================
18/01/2024 19:13:23 base._run                                L0066 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#122: [cmp227-6] AnsibleModule::shell executing...
18/01/2024 20:16:15 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ysmanman** [comment]
@arlakshm @kenneth-arista
