### ISSUE TITLE
snappi-multiDUT script fails with single dut runs.

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-mgmt#11555]
https://github.com/sonic-net/sonic-mgmt/blob/f3b002806d3b03fddf1615686241dcbfa2e66fcf/tests/snappi_tests/test_multidut_snappi.py#L112

When running this script with a single DUT, we see this error. Pls handle it in the script, for single-dut. It should be able to handle a single DUT with multi-ASIC as well.

INFO:SectionStartLogger:==================== snappi_tests/test_multidut_snappi.py::test_snappi[linecard_configuration_set0-chassis_multi_line_card_multi_asic] call ====================
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1761, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 192, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/tests/snappi_tests/test_multidut_snappi.py", line 112, in test_snappi
    dut_list = random.sample(duthosts, 2)
  File "/usr/lib/python3.8/random.py", line 359, in sample
    raise TypeError("Population must be a sequence or set.  For dicts, use list(d).")
TypeError: Population must be a sequence or set.  For dicts, use list(d).

**Comment by rraghav-cisco** [comment]
@kamalsahu0001 for viz.

**Comment by rraghav-cisco** [comment]
The problem went away after setting correct values in the tests/snappi_tests/variables.py.
