### ISSUE TITLE
Traceback in 202311 branch running snappi_tests/lacp/

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-mgmt#12262]
Seeing this error when running 202311 based tests/snappi_tests/lacp/test_add_remove_link_from_dut.py.
I saw that the protocol is defined in the file:/usr/local/lib/python3.8/dist-packages/snappi/snappi.py
So I need help understanding why this error appears.
Thanks in advance: @selldinesh , @isgmano , and @kamalsahu0001 

ERROR:root:Traceback (most recent call last):
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 1772, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/tests/snappi_tests/lacp/test_add_remove_link_from_dut.py", line 52, in test_lacp_add_remove_link_from_dut
    run_lacp_add_remove_link_from_dut(snappi_api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 41, in run_lacp_add_remove_link_from_dut
    tgen_bgp_config = __tgen_bgp_config(api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 153, in __tgen_bgp_config
    lp.protocol.lacp.actor_system_id = "00:10:00:00:11:11"
AttributeError: 'LagPort' object has no attribute 'protocol'

ERROR    root:__init__.py:40 Traceback (most recent call last):
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 1772, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/tests/snappi_tests/lacp/test_add_remove_link_from_dut.py", line 52, in test_lacp_add_remove_link_from_dut
    run_lacp_add_remove_link_from_dut(snappi_api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 41, in run_lacp_add_remove_link_from_dut
    tgen_bgp_config = __tgen_bgp_config(api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 153, in __tgen_bgp_config
    lp.protocol.lacp.actor_system_id = "00:10:00:00:11:11"
AttributeError: 'LagPort' object has no attribute 'protocol'

**Comment by selldinesh** [comment]
@rraghav-cisco Fix has been provided on https://github.com/sonic-net/sonic-mgmt/pull/12279 for this issue. The current version of  snappi-convergence doesnt support the older code

**Comment by rraghav-cisco** [comment]
@selldinesh : After applying the PR, this new problem comes up:
```
ERROR    root:__init__.py:40 Traceback (most recent call last):
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 1772, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/tests/snappi_tests/lacp/test_add_remove_link_from_dut.py", line 52, in test_lacp_add_remove_link_from_dut
    run_lacp_add_remove_link_from_dut(snappi_api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 41, in run_lacp_add_remove_link_from_dut
    tgen_bgp_config = __tgen_bgp_config(api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 152, in __tgen_bgp_config
    lag0.protocol.lacp.actor_system_id = "00:10:00:00:11:11"
AttributeError: 'Lag' object has no attribute 'protocol'
```

**Comment by rraghav-cisco** [comment]
@selldinesh : Any update ?

**Comment by selldinesh** [comment]
@rraghav-cisco may i know what is the snappi version that you are using ?

**Comment by rraghav-cisco** [comment]
@selldinesh , I am using:
snappi                             0.7.44
snappi-convergence                 0.2.2
snappi-ixnetwork                   0.7.12

**Comment by selldinesh** [comment]
@rraghav-cisco can you please use the below version
snappi                           0.9.1
snappi-convergence               0.4.1
snappi-ixnetwork                 0.9.1

**Comment by rraghav-cisco** [comment]
@selldinesh , after installing the requested versions, I see a new problem:

```
sonic@snappi-202311-sonic-mgmt:/data/tests$ pip3 list | grep -i snappi
snappi                           0.9.1
snappi-convergence               0.4.1
snappi-ixnetwork                 0.9.1
WARNING: There was an error checking the latest version of pip.
sonic@snappi-202311-sonic-mgmt:/data/tests$ 
```


```
snappi_ixnetwork.exceptions.SnappiIxnException:   File "/home/sonic/.local/lib/python3.8/site-packages/snappi_ixnetwork/snappi_convergence_api.py", line 136, in set_state
    self._api.ngpf.set_protocol_state(payload.protocol)
  File "/home/sonic/.local/lib/python3.8/site-packages/snappi_ixnetwork/device/ngpf.py", line 253, in set_protocol_state
    self.api._ixnetwork.StartAllProtocols("sync")
  File "/home/sonic/.local/lib/python3.8/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py", line 2736, in StartAllProtocols
    return self._execute("startAllProtocols", payload=payload, response_object=None)
  File "/home/sonic/.local/lib/python3.8/site-packages/ixnetwork_restpy/base.py", line 452, in _execute
    response = self._connection._execute(url, payload)
  File "/home/sonic/.local/lib/python3.8/site-packages/ixnetwork_restpy/connection.py", line 289, in _execute
    return self._send_recv("POST", url, payload)
  File "/home/sonic/.local/lib/python3.8/site-packages/ixnetwork_restpy/connection.py", line 572, in _send_recv
    return self._poll()
  File "/home/sonic/.local/lib/python3.8/site-packages/ixnetwork_restpy/connection.py", line 640, in _poll
    return self._process_response_status_code(
  File "/home/sonic/.local/lib/python3.8/site-packages/ixnetwork_restpy/connection.py", line 476, in _process_response_status_code
    raise BadRequestError(message, response.status_code)
  The maximum number of interfaces has been exceeded.
Cannot add an additional 1 interfaces since LACP only supports 1 interfaces on NOVUS-M100GE8Q28+FAN ports and 1 interfaces have been previously allocated.
To fix the problem, decrease the number of devices, or use a port type that supports more interfaces.
System Exception Caught. Exception Text: The maximum number of interfaces has been exceeded.
Cannot add an additional 1 interfaces since LACP only supports 1 interfaces on NOVUS-M100GE8Q28+FAN ports and 1 interfaces have been previously allocated.
To fix the problem, decrease the number of devices, or use a port type that supports more interfaces.
```

**Comment by rraghav-cisco** [comment]
@selldinesh : Any suggestions?

**Comment by rraghav-cisco** [comment]
@selldinesh : You fixed it in https://github.com/sonic-net/sonic-mgmt/pull/10737. Pls propagate it to all other branches.
