### ISSUE TITLE
[Vlan][Dual-Tor] The vlan ping test is failing on dualtor topology

### ISSUE THREAD

**Issue by AnantKishorSharma** [sonic-net/sonic-mgmt#12302]
**Description**

We see this neigh add cmd failure sporadically in test_vlan_ping.py in dualtor runs 

**Steps to reproduce the issue:**
1. Run the vlan ping test on dualtor testbed
2.
3.

**Describe the results you received:**
```
sudo ip -6 neigh add fc02:1000::e lladdr ce:5d:b8:6b:8f:0e dev Vlan1000 cmd failed

Log excerpts:
03/03/2024 17:25:50 __init__._log_sep_line                   L0170 INFO   | ==================== vlan/test_vlan_ping.py::test_vlan_ping call ====================
03/03/2024 17:25:50 test_vlan_ping.test_vlan_ping            L0176 INFO   | initializing setup for ipv4 and ipv6
03/03/2024 17:25:50 test_vlan_ping.static_neighbor_entry     L0023 DEBUG  | adding ipv4 static arp entry for ip 192.168.0.2 on DUT
03/03/2024 17:25:50 base._run                                L0067 DEBUG  | /var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/common/devices/multi_asic.py::_run_on_asics#128: [str2-8102-04] AnsibleModule::shell, args=["sudo arp -s 192.168.0.2 ce:5d:b8:6b:8f:0e"], kwargs={}
03/03/2024 17:25:50 base._run                                L0104 DEBUG  | /var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/common/devices/multi_asic.py::_run_on_asics#128: [str2-8102-04] AnsibleModule::shell Result => {"changed": true, "stdout": "", "stderr": "", "rc": 0, "cmd": "sudo arp -s 192.168.0.2 ce:5d:b8:6b:8f:0e", "start": "2024-03-03 17:25:50.845935", "end": "2024-03-03 17:25:50.862804", "delta": "0:00:00.016869", "msg": "", "invocation": {"module_args": {"_raw_params": "sudo arp -s 192.168.0.2 ce:5d:b8:6b:8f:0e", "_uses_shell": true, "warn": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}, "stdout_lines": [], "stderr_lines": [], "_ansible_no_log": null, "failed": false}
03/03/2024 17:25:50 test_vlan_ping.static_neighbor_entry     L0034 DEBUG  | adding ipv6 static arp entry for ip fc02:1000::e on DUT
03/03/2024 17:25:50 base._run                                L0067 DEBUG  | /var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/common/devices/multi_asic.py::_run_on_asics#128: [str2-8102-04] AnsibleModule::shell, args=["sudo ip -6 neigh add fc02:1000::e lladdr ce:5d:b8:6b:8f:0e dev Vlan1000"], kwargs={}
03/03/2024 17:25:51 base._run                                L0104 DEBUG  | /var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/common/devices/multi_asic.py::_run_on_asics#128: [str2-8102-04] AnsibleModule::shell Result => {"failed": true, "changed": true, "stdout": "", "stderr": "RTNETLINK answers: File exists", "rc": 2, "cmd": "sudo ip -6 neigh add fc02:1000::e lladdr ce:5d:b8:6b:8f:0e dev Vlan1000", "start": "2024-03-03 17:25:51.283399", "end": "2024-03-03 17:25:51.300159", "delta": "0:00:00.016760", "msg": "non-zero return code", "invocation": {"module_args": {"_raw_params": "sudo ip -6 neigh add fc02:1000::e lladdr ce:5d:b8:6b:8f:0e dev Vlan1000", "_uses_shell": true, "warn": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}, "stdout_lines": [], "stderr_lines": ["RTNETLINK answers: File exists"], "_ansible_no_log": null}
03/03/2024 17:25:51 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/vlan/test_vlan_ping.py", line 177, in test_vlan_ping
    static_neighbor_entry(duthost, ptfhost_info, "add")
  File "/var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/vlan/test_vlan_ping.py", line 35, in static_neighbor_entry
    duthost.shell(
  File "/var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/common/devices/multi_asic.py", line 128, in _run_on_asics
    return getattr(self.sonichost, self.multi_asic_attr)(*module_args, **complex_args)
  File "/var/src/sonic-mgmt_vms28-dual-t0-8102_6551d780a6069aa8dc7c1c2e/tests/common/devices/base.py", line 127, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "sudo ip -6 neigh add fc02:1000::e lladdr ce:5d:b8:6b:8f:0e dev Vlan1000", "delta": "0:00:00.016760", "end": "2024-03-03 17:25:51.300159", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2024-03-03 17:25:51.283399", "stderr": "RTNETLINK answers: File exists", "stderr_lines": ["RTNETLINK answers: File exists"], "stdout": "", "stdout_lines": []}
```

**Describe the results you expected:**
neigh add cmd should have executed without error

**Additional information you deem important:**
Seen in 202305 and 202311 versions on Cisco-8000

**Comment by AnantKishorSharma** [comment]
@bpar9 @wsycqyz  - Please assign this to me. The fix is available in 202405 onwards, please approve the master PR for other active branches if needed.
