### ISSUE TITLE
[Bug]: Tests failing due to log match on `WARNING kernel: [87791.579181] pcieport 0000:05:05.0:   device [10b5:8717] error status/mask=00000001/0000a000`

### ISSUE THREAD

**Issue by arista-nwolfe** [sonic-net/sonic-mgmt#13315]
### Issue Description

Tests failing on master and 202405 due to kernel warnings in `/var/log/syslog`
```
Match Messages:
2024 Jun 14 20:55:27.633513 nfc407-7 WARNING kernel: [87791.579181] pcieport 0000:05:05.0:   device [10b5:8717] error status/mask=00000001/0000a000
```

The problem is the regex `r, "kernel:.*\serr"` in `loganalyzer_common_match.txt` matches this log.
https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_match.txt#L4

So likely need to ignore this in `loganalyzer_common_ignore.txt`

Here is the surrounding syslog lines:
```
INFO kernel: [116593.150224] pcieport 0000:00:03.1: AER: Corrected error received: 0000:05:03.0
WARNING kernel: [116593.150261] pcieport 0000:05:03.0: PCIe Bus Error: severity=Corrected, type=Physical Layer, (Receiver ID)
WARNING kernel: [116593.150269] pcieport 0000:05:03.0:   device [10b5:8717] error status/mask=00002001/0000a000
WARNING kernel: [116593.150280] pcieport 0000:05:03.0:    [ 0] RxErr                  (First)
```

### Results you see

```
E               Traceback:
E               Traceback (most recent call last):
E                 File "/data/tests/common/helpers/parallel.py", line 35, in run
E                   Process.run(self)
E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/data/tests/common/helpers/parallel.py", line 245, in wrapper
E                   target(*args, **kwargs)
E                 File "/data/tests/common/plugins/loganalyzer/__init__.py", line 45, in analyze_logs
E                   dut_analyzer.analyze(markers[node.hostname], fail_test, store_la_logs=store_la_logs)
E                 File "/data/tests/common/plugins/loganalyzer/loganalyzer.py", line 409, in analyze
E                   self._verify_log(analyzer_summary)
E                 File "/data/tests/common/plugins/loganalyzer/loganalyzer.py", line 140, in _verify_log
E                   raise LogAnalyzerError(result_str)
E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 3
E               expected_match: 0
E               expected_missing_match: 0
E
E               Match Messages:
E               2024 Jun 14 20:55:27.633513 nfc407-7 WARNING kernel: [87791.579181] pcieport 0000:05:05.0:   device [10b5:8717] error status/mask=00000001/0000a000
E
E               2024 Jun 14 20:57:03.989494 nfc407-7 WARNING kernel: [87887.929144] pcieport 0000:05:05.0:   device [10b5:8717] error status/mask=00000001/0000a000
E
E               2024 Jun 14 20:58:02.565491 nfc407-7 WARNING kernel: [87946.504690] pcieport 0000:05:05.0:   device [10b5:8717] error status/mask=00000001/0000a000
```

### Results you expected to see

This log doesn't result in sonic-mgmt tests failing

### Is it platform specific

generic

### Output of `show version`

```shell
show version

SONiC Software Version: SONiC.branch.202405-ars.6720793b-buildimage.origin.202405-review.359992.1-dbg-2024.06.12.20.54
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: 99554e765
Build date: Thu Jun 13 03:44:44 UTC 2024
Built by: jenkins@jenkins-arsonic-k8s-7-n6lf2

Platform: x86_64-arista_7800r3ak_36dm2_lc
HwSKU: Arista-7800R3AK-36DM2-C36
ASIC: broadcom
ASIC Count: 2
Serial Number: SSN21060178
Model Number: 7800R3AK-36DM2-LC
Hardware Revision: 29.00
Uptime: 22:46:09 up 1 day,  4:54,  1 user,  load average: 1.55, 1.82, 2.15
Date: Fri 14 Jun 2024 22:46:09
```

**Comment by arista-nwolfe** [comment]
We haven't seen this issue hit again since the issue was created.
Closing issue, will reopen if seen again.

**Comment by abdosi** [comment]
@arista-nwolfe : how this got fixed ?

**Comment by arista-nwolfe** [comment]
> @arista-nwolfe : how this got fixed ?

We aren't sure but we don't see this log anymore so I closed this bug.
