### ISSUE TITLE
[Bug]: Syslog error releated to tacacs, and sshd seen While Running Test cases

### ISSUE THREAD

**Issue by kaushiksrivatsav** [sonic-net/sonic-mgmt#13509]
### Issue Description

seeing syslog errors seeing while running Test cases 
"ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress"
"ERR sshd[1733802]: auth fail: Password incorrect. user: root"

### Results you see

    2024 Jul  1 09:28:10.755761 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:30:05.547499 str-marvell-acs-1 ERR sshd[1733802]: auth fail: Password incorrect. user: root

### Results you expected to see

Syslog log errors not be not seeing 

### Is it platform specific

marvell

### Relevant log output

```shell
pt_assert(
                    False,
                    'Processes "{}" failed with exit code "{}"\nException:\n{}\nTraceback:\n{}'.format(
                        list(failed_processes.keys()), p_exitcode, p_exception, p_traceback
                    )
                )
E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>']" failed with exit code "1"
E               Exception:
E               match: 46
E               expected_match: 0
E               expected_missing_match: 0
E
E               Match Messages:
E               2024 Jul  1 09:09:14.925766 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:05.521675 str-marvell-acs-1 ERR sshd[1708197]: auth fail: Password incorrect. user: root
E
E               2024 Jul  1 09:10:08.271854 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:14.343683 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:30.309034 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:46.337084 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:04.012620 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:20.423718 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:36.584672 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:52.852364 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:09.115931 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:25.095315 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:41.059645 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:57.276188 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:13:13.388232 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:13:29.339711 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:13:45.372775 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:01.629487 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:17.680187 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:33.739580 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:49.916098 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:15:05.975917 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:20:06.521689 str-marvell-acs-1 ERR sshd[1720694]: auth fail: Password incorrect. user: root
E
E               2024 Jul  1 09:21:31.066177 str-marvell-acs-1 ERR syncd#syncd: cpssHalHostIf.c:1996 cpssDxChNetIfSdmaSyncTxPacketSend returned with status 0x10017 on packet size 183 on dev 0 port 46
E
E               2024 Jul  1 09:21:31.066753 str-marvell-acs-1 ERR syncd#syncd: xpsPacketDrv.c:791 cpssHalHostIfCPUtoPPPacketTransmit failed
E
E               2024 Jul  1 09:23:14.989699 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:23:20.923571 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:23:36.856371 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:23:52.952118 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:08.983880 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:24.936968 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:41.105621 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:57.251455 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:25:13.339703 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:25:29.319720 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:25:45.307320 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:01.871451 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:18.191421 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:34.265098 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:50.344352 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:06.428459 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:22.440160 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:38.467743 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:54.641135 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:28:10.755761 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:30:05.547499 str-marvell-acs-1 ERR sshd[1733802]: auth fail: Password incorrect. user: root
E
E               Traceback:
E               Traceback (most recent call last):
E                 File "/var/AzDevOps/21052024/sonic-mgmt/tests/common/helpers/parallel.py", line 35, in run
E                   Process.run(self)
E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/var/AzDevOps/21052024/sonic-mgmt/tests/common/helpers/parallel.py", line 245, in wrapper
E                   target(*args, **kwargs)
E                 File "/var/AzDevOps/21052024/sonic-mgmt/tests/common/plugins/loganalyzer/__init__.py", line 45, in analyze_logs
E                   dut_analyzer.analyze(markers[node.hostname], fail_test, store_la_logs=store_la_logs)
E                 File "/var/AzDevOps/21052024/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 409, in analyze
E                   self._verify_log(analyzer_summary)
E                 File "/var/AzDevOps/21052024/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 140, in _verify_log
E                   raise LogAnalyzerError(result_str)
E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 46
E               expected_match: 0
E               expected_missing_match: 0
E
E               Match Messages:
E               2024 Jul  1 09:09:14.925766 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:05.521675 str-marvell-acs-1 ERR sshd[1708197]: auth fail: Password incorrect. user: root
E
E               2024 Jul  1 09:10:08.271854 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:14.343683 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:30.309034 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:10:46.337084 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:04.012620 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:20.423718 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:36.584672 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:11:52.852364 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:09.115931 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:25.095315 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:41.059645 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:12:57.276188 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:13:13.388232 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:13:29.339711 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:13:45.372775 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:01.629487 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:17.680187 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:33.739580 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:14:49.916098 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:15:05.975917 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:20:06.521689 str-marvell-acs-1 ERR sshd[1720694]: auth fail: Password incorrect. user: root
E
E               2024 Jul  1 09:21:31.066177 str-marvell-acs-1 ERR syncd#syncd: cpssHalHostIf.c:1996 cpssDxChNetIfSdmaSyncTxPacketSend returned with status 0x10017 on packet size 183 on dev 0 port 46
E
E               2024 Jul  1 09:21:31.066753 str-marvell-acs-1 ERR syncd#syncd: xpsPacketDrv.c:791 cpssHalHostIfCPUtoPPPacketTransmit failed
E
E               2024 Jul  1 09:23:14.989699 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:23:20.923571 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:23:36.856371 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:23:52.952118 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:08.983880 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:24.936968 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:41.105621 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:24:57.251455 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:25:13.339703 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:25:29.319720 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:25:45.307320 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:01.871451 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:18.191421 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:34.265098 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:26:50.344352 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:06.428459 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:22.440160 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:38.467743 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:27:54.641135 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:28:10.755761 str-marvell-acs-1 ERR ps: nss_tacplus: failed to connect TACACS+ server 172.17.0.6:49, ret=-8: Operation now in progress
E
E               2024 Jul  1 09:30:05.547499 str-marvell-acs-1 ERR sshd[1733802]: auth fail: Password incorrect. user: root

alive      = []
args       = [{'str-marvell-acs-1': <tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzer object at 0x7f97b44e15e0>}, {'str-marvell-acs-1': 'test_max_limit[techsupport].2024-07-01-09:09:02'}]
concurrent_tasks = 24
delta_time = datetime.timedelta(seconds=10, microseconds=399094)
end_time   = datetime.datetime(2024, 7, 1, 9, 36, 27, 23115)
failed_processes = {'analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>': {'exception': ('Log Analyzer Error- Matches found, please che... 09:30:05.547499 str-marvell-acs-1 ERR sshd[1733802]: auth fail: Password incorrect. user: root\n\n'), 'exit_code': 1}}
force_terminate = <function parallel_run.<locals>.force_terminate at 0x7f97b41caaf0>
gone       = [<SonicProcess name='analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>' pid=10695 parent=7371 stopped exitcode=1>]
init_result = None
kwargs     = {'fail_test': True, 'node': <MultiAsicSonicHost str-marvell-acs-1>, 'results': <DictProxy object, typeid 'dict' at 0x7f97b5a09fa0>, 'store_la_logs': False}
node       = <MultiAsicSonicHost str-marvell-acs-1>
nodes      = []
nodes_list = [<MultiAsicSonicHost str-marvell-acs-1>]
on_terminate = <function parallel_run.<locals>.on_terminate at 0x7f97b5a4b550>
p_exception = 'Log Analyzer Error- Matches found, please check errors in log'
p_exitcode = 1
p_traceback = 'Traceback (most recent call last):\n  File "/var/AzDevOps/21052024/sonic-mgmt/tests/common/helpers/parallel.py", line...ress\n\n2024 Jul  1 09:30:05.547499 str-marvell-acs-1 ERR sshd[1733802]: auth fail: Password incorrect. user: root\n\n'
process    = {'exception': ('Log Analyzer Error- Matches found, please check errors in log', 'Traceback (most recent call last):\n ...1 09:30:05.547499 str-marvell-acs-1 ERR sshd[1733802]: auth fail: Password incorrect. user: root\n\n'), 'exit_code': 1}
process_name = 'analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>'
results    = <DictProxy object, typeid 'dict' at 0x7f97b5a09fa0>
start_time = datetime.datetime(2024, 7, 1, 9, 36, 16, 624021)
target     = <function reset_ansible_local_tmp.<locals>.wrapper at 0x7f97b8fa5790>
tasks_done = 1
tasks_running = 0
timeout    = 120
total_tasks = 1
total_timeout = 120
worker     = <SonicProcess name='analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>' pid=10695 parent=7371 stopped exitcode=1>
workers    = []

common/helpers/parallel.py:214: Failed
```

### Output of `show version`

```shell
SONiC Software Version: SONiC.202405.0-dirty-20240612.064353
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: 7bafdab86
Build date: Wed Jun 12 07:07:26 UTC 2024
Built by: marvell@cpss-testvm1

Platform: x86_64-marvell_db98cx8540_16cd-r0
HwSKU: db98cx8540_16cd
ASIC: marvell
ASIC Count: 1
Serial Number: NA
Model Number: NA
Hardware Revision: N/A
Uptime: 08:18:36 up 38 min,  1 user,  load average: 3.20, 2.48, 2.02
Date: Mon 01 Jul 2024 08:18:36

Docker images:
REPOSITORY                    TAG                              IMAGE ID       SIZE
docker-syncd-mrvl-rpc         202405.0-dirty-20240612.064353   f643d7ce193c   585MB
docker-syncd-mrvl-rpc         latest                           f643d7ce193c   585MB
docker-macsec                 latest                           eb50c20a2246   347MB
docker-dhcp-relay             latest                           58e72a51d4af   325MB
docker-teamd                  202405.0-dirty-20240612.064353   9384f2f48e12   344MB
docker-teamd                  latest                           9384f2f48e12   344MB
docker-sonic-mgmt-framework   202405.0-dirty-20240612.064353   13aa80364eb5   402MB
docker-sonic-mgmt-framework   latest                           13aa80364eb5   402MB
docker-snmp                   202405.0-dirty-20240612.064353   e1ddbd3c38f9   355MB
docker-snmp                   latest                           e1ddbd3c38f9   355MB
docker-sflow                  202405.0-dirty-20240612.064353   4882fb502e7c   345MB
docker-sflow                  latest                           4882fb502e7c   345MB
docker-router-advertiser      202405.0-dirty-20240612.064353   b44a98aca7c4   316MB
docker-router-advertiser      latest                           b44a98aca7c4   316MB
docker-platform-monitor       202405.0-dirty-20240612.064353   499aac892c88   441MB
docker-platform-monitor       latest                           499aac892c88   441MB
docker-orchagent              202405.0-dirty-20240612.064353   2b06b769aae5   357MB
docker-orchagent              latest                           2b06b769aae5   357MB
docker-nat                    202405.0-dirty-20240612.064353   6ff5537aa194   347MB
docker-nat                    latest                           6ff5537aa194   347MB
docker-mux                    202405.0-dirty-20240612.064353   8d9a7bc2bcb1   367MB
docker-mux                    latest                           8d9a7bc2bcb1   367MB
docker-lldp                   202405.0-dirty-20240612.064353   b5fa4ebe7191   361MB
docker-lldp                   latest                           b5fa4ebe7191   361MB
docker-sonic-gnmi             202405.0-dirty-20240612.064353   93bbd8c3d57f   400MB
docker-sonic-gnmi             latest                           93bbd8c3d57f   400MB
docker-fpm-frr                202405.0-dirty-20240612.064353   494a1138b32e   376MB
docker-fpm-frr                latest                           494a1138b32e   376MB
docker-eventd                 202405.0-dirty-20240612.064353   089be6e4318c   315MB
docker-eventd                 latest                           089be6e4318c   315MB
docker-database               202405.0-dirty-20240612.064353   257a27b56050   324MB
docker-database               latest                           257a27b56050   324MB
```

**Comment by yxieca** [comment]
@kaushiksrivatsav can you check if you DUT can reach IP 172.17.0.6? (ping, traceroute). It could be a test environment issue. Can you check if this is a duplicate of #13708?
