### ISSUE TITLE
[Bug]: config_sonic_basedon_testbed.yml creates an empty golden_config_db.json file for non mx platforms

### ISSUE THREAD

**Issue by mannytaheri** [sonic-net/sonic-mgmt#13987]
### Issue Description

config_sonic_basedon_testbed.yml creates an empty golden_config_db.json file under /etc/sonic for non mx platforms.
When this empty file exist db_migration fails for all asics for non mx platforms.
This yml file should be modified to create that file for mx platform and ignore all other platforms

As a work around, this file can be deleted manully When it exists so db_migration can succeed.

### Results you see

An empty golden_config_db.json file under /etc/sonic for non mx platforms

### Results you expected to see

golden_config_db.json file should not be created for non mx platforms.

### Is it platform specific

generic

### Relevant log output

```shell
E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost ixre-egl-board191>']" failed with exit code "1"
E               Exception:
E               match: 16
E               expected_match: 0
E               expected_missing_match: 0
E               
E               Match Messages:
E               2024 Jul 31 16:34:30.601211 ixre-egl-board191 ERR db_migrator: Caught exception while trying to load golden config: 'asic0'
E               
E               2024 Jul 31 16:34:31.668800 ixre-egl-board191 ERR db_migrator: Caught exception while trying to load golden config: 'asic1'
E               
E            
E               Traceback:
E               Traceback (most recent call last):
E                 File "/data/tests/common/helpers/parallel.py", line 35, in run
E                   Process.run(self)
E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/data/tests/common/helpers/parallel.py", line 245, in wrapper
E                   target(*args, **kwargs)
E                 File "/data/tests/common/plugins/loganalyzer/__init__.py", line 45, in analyze_logs
E                   dut_analyzer.analyze(markers[node.hostname], fail_test, store_la_logs=store_la_logs)
E                 File "/data/tests/common/plugins/loganalyzer/loganalyzer.py", line 409, in analyze
E                   self._verify_log(analyzer_summary)
E                 File "/data/tests/common/plugins/loganalyzer/loganalyzer.py", line 140, in _verify_log
E                   raise LogAnalyzerError(result_str)
E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 16
E               expected_match: 0
E               expected_missing_match: 0
E               
E               Match Messages:
E               2024 Jul 31 16:34:30.601211 ixre-egl-board191 ERR db_migrator: Caught exception while trying to load golden config: 'asic0'
E               
E               2024 Jul 31 16:34:31.668800 ixre-egl-board191 ERR db_migrator: Caught exception while trying to load golden config: 'asic1'
```

### Output of `show version`

```shell
Latest master
```

**Comment by rlhui** [comment]
@xincunli-sonic please help check this? thanks.

**Comment by xincunli-sonic** [comment]
The image fix has done, please use the latest master to build a new image to do the test.

https://github.com/sonic-net/sonic-utilities/pull/3670
