### ISSUE TITLE
[Bug]: Test issues in tests/gnmi/test_gnoi_killprocess.py

### ISSUE THREAD

**Issue by congh-nvidia** [sonic-net/sonic-mgmt#15507]
### Issue Description

I have run the test tests/gnmi/test_gnoi_killprocess.py against the public master image master.692211-c8e588808, and some cases failed due to test issues:
1. There is no topology mark in the test, when run it on a t1 topology, the dhcp_relay test case fails because dhcp_relay is not enabled in t1. There should be a logic for dhcp_relay case to skip t1 topology. And it's better to add the pytest.mark.topology("any") for the entire test.
```
Failed: dhcp_relay should be running before KillProcess test attempts to kill this process
```
2. The restapi case failed because there is no restapi container in the image.
3. The pmon case failed because it is right after the swss case, and after the swss is killed, all containers will restart. When the pmon case starts, the pmon container is not yet ready. Need add a wait until in the swss case to ensure all containers are up.
```
Failed: pmon should be running before KillProcess test attempts to kill this process
```
4. The telemetry case failed because there is no telemetry container, the telemetry service is moved to gnmi container. Should we still have this test case?

### Results you see

4 test cases failed:
test_gnoi_killprocess_then_restart[dhcp_relay-True-]
test_gnoi_killprocess_then_restart[restapi-True-]
test_gnoi_killprocess_then_restart[pmon-True-]
test_gnoi_killprocess_then_restart[telemetry-True-]

### Results you expected to see

No failures.

### Is it platform specific

generic

### Output of `show version`

```shell
SONiC Software Version: SONiC.master.692211-c8e588808
SONiC OS Version: 12
Distribution: Debian 12.6
Kernel: 6.1.0-22-2-amd64
Build commit: c8e588808
Build date: Mon Nov 11 12:08:50 UTC 2024
Built by: azureuser@f6342405c000000

Platform: x86_64-mlnx_msn4700-r0
HwSKU: Mellanox-SN4700-O32
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2022X08595
Model Number: MSN4700-WS2FO
Hardware Revision: A7
Uptime: 09:04:52 up 27 min,  1 user,  load average: 0.90, 1.11, 0.99
Date: Tue 12 Nov 2024 09:04:52

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-syncd-mlnx             latest                    e222d95b9ec8   768MB
docker-syncd-mlnx             master.692211-c8e588808   e222d95b9ec8   768MB
docker-orchagent              latest                    7e75bb9d3a1c   355MB
docker-orchagent              master.692211-c8e588808   7e75bb9d3a1c   355MB
docker-teamd                  latest                    580bb7459c6f   342MB
docker-teamd                  master.692211-c8e588808   580bb7459c6f   342MB
docker-sflow                  latest                    a8d2932050b2   343MB
docker-sflow                  master.692211-c8e588808   a8d2932050b2   343MB
docker-nat                    latest                    0365146324ae   345MB
docker-nat                    master.692211-c8e588808   0365146324ae   345MB
docker-fpm-frr                latest                    52843c640157   374MB
docker-fpm-frr                master.692211-c8e588808   52843c640157   374MB
docker-macsec                 latest                    39ac9fc661ee   345MB
docker-platform-monitor       latest                    2fb7a9375c1f   616MB
docker-platform-monitor       master.692211-c8e588808   2fb7a9375c1f   616MB
docker-dhcp-relay             latest                    a43820ee8d22   322MB
docker-snmp                   latest                    99d6b1cdfae2   352MB
docker-snmp                   master.692211-c8e588808   99d6b1cdfae2   352MB
docker-sonic-mgmt-framework   latest                    8a51115ec316   399MB
docker-sonic-mgmt-framework   master.692211-c8e588808   8a51115ec316   399MB
docker-eventd                 latest                    a769bf13ab0c   313MB
docker-eventd                 master.692211-c8e588808   a769bf13ab0c   313MB
docker-router-advertiser      latest                    5031cbbdb5d8   313MB
docker-router-advertiser      master.692211-c8e588808   5031cbbdb5d8   313MB
docker-mux                    latest                    26de0fe08a30   365MB
docker-mux                    master.692211-c8e588808   26de0fe08a30   365MB
docker-lldp                   latest                    bc67db09b91b   359MB
docker-lldp                   master.692211-c8e588808   bc67db09b91b   359MB
docker-sonic-gnmi             latest                    a8998756e16f   397MB
docker-sonic-gnmi             master.692211-c8e588808   a8998756e16f   397MB
docker-database               latest                    013b55ced190   322MB
docker-database               master.692211-c8e588808   013b55ced190   322MB
```

**Comment by congh-nvidia** [comment]
Hi @isabelmsft , could you please take a look at this issue?

**Comment by hdwhdw** [comment]
Assigning to myself. Working on https://github.com/sonic-net/sonic-mgmt/pull/16303 as a fix. 

Additionally in my local run, local analyzer also report problem when killing snmp:

```
E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost vlab-01>']" failed with exit code "1"
E               Exception:
E               match: 2
E               expected_match: 0
E               expected_missing_match: 0
E               
E               Match Messages:
E               2025 Jan 16 20:24:46.622122 vlab-01 ERR sonic-db-cli: :- guard: RedisReply catches system_error: command: *9\r\n$4\r\nHSET\r\n$25\r\nDEVICE_METADATA|localhost\r\n$21\r\nchassis_serial_number\r\n$6\r\nFailed\r\n$2\r\nto\r\n$4\r\nread\r\n$6\r\nsystem\r\n$6\r\nEEPROM\r\n$4\r\ninfo\r\n, reason: ERR wrong number of arguments for 'hset' command: Input/output error
E               
E               2025 Jan 16 20:24:46.622209 vlab-01 INFO snmp.sh[715493]: RedisReply catches system_error: command: *9\r\n$4\r\nHSET\r\n$25\r\nDEVICE_METADATA|localhost\r\n$21\r\nchassis_serial_number\r\n$6\r\nFailed\r\n$2\r\nto\r\n$4\r\nread\r\n$6\r\nsystem\r\n$6\r\nEEPROM\r\n$4\r\ninfo\r\n, reason: ERR wrong number of arguments for 'hset' command: Input/output error: Input/output error
E               
E               Traceback:
E               Traceback (most recent call last):
E                 File "/data/sonic-mgmt/tests/common/helpers/parallel.py", line 35, in run
E                   Process.run(self)
E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/data/sonic-mgmt/tests/common/helpers/parallel.py", line 245, in wrapper
E                   target(*args, **kwargs)
E                 File "/data/sonic-mgmt/tests/common/plugins/loganalyzer/__init__.py", line 45, in analyze_logs
E                   dut_analyzer.analyze(markers[node.hostname], fail_test, store_la_logs=store_la_logs)
E                 File "/data/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 409, in analyze
E                   self._verify_log(analyzer_summary)
E                 File "/data/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 140, in _verify_log
E                   raise LogAnalyzerError(result_str)
E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 2
E               expected_match: 0
E               expected_missing_match: 0
E               
E               Match Messages:
E               2025 Jan 16 20:24:46.622122 vlab-01 ERR sonic-db-cli: :- guard: RedisReply catches system_error: command: *9\r\n$4\r\nHSET\r\n$25\r\nDEVICE_METADATA|localhost\r\n$21\r\nchassis_serial_number\r\n$6\r\nFailed\r\n$2\r\nto\r\n$4\r\nread\r\n$6\r\nsystem\r\n$6\r\nEEPROM\r\n$4\r\ninfo\r\n, reason: ERR wrong number of arguments for 'hset' command: Input/output error
E               
E               2025 Jan 16 20:24:46.622209 vlab-01 INFO snmp.sh[715493]: RedisReply catches system_error: command: *9\r\n$4\r\nHSET\r\n$25\r\nDEVICE_METADATA|localhost\r\n$21\r\nchassis_serial_number\r\n$6\r\nFailed\r\n$2\r\nto\r\n$4\r\nread\r\n$6\r\nsystem\r\n$6\r\nEEPROM\r\n$4\r\ninfo\r\n, reason: ERR wrong number of arguments for 'hset' command: Input/output error: Input/output error
```

suspect this is image problem.
