### ISSUE TITLE
[Snappi] [Bug]: TypeError in multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

### ISSUE THREAD

**Issue by sdszhang** [sonic-net/sonic-mgmt#15799]
### Issue Description

snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py::test_pfc_pause_single_lossy_prio[multidut_port_info0-xxxxxx-lc1-1|0] 
-------------------------------- live log call ---------------------------------
15:33:38 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py", line 70, in test_pfc_pause_single_lossy_prio
    run_pfc_test(api=snappi_api,
  File "/var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/snappi_tests/multidut/pfc/files/multidut_helper.py", line 270, in run_pfc_test
    verify_basic_test_flow(flow_metrics=tgen_flow_stats,
  File "/var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/common/snappi_tests/traffic_generation.py", line 533, in verify_basic_test_flow
    exp_test_flow_rx_pkts = data_flow_config["flow_rate_percent"] / 100.0 * speed_gbps \
TypeError: unsupported operand type(s) for /: 'dict' and 'float'

data_flow_config["flow_rate_percent"] is assigned as dictionary in #15589, and result in this error.

### Results you see

data type error

### Results you expected to see

test case should pass.

### Is it platform specific

generic

**Comment by yxieca** [comment]
@sdszhang there seems to be a fix already? Can this issue be closed now?

**Comment by sdszhang** [comment]
resolved in #15800
