### ISSUE TITLE
[Bug]: IXIA Protocols are not stopped in 10 seconds 

### ISSUE THREAD

**Issue by auspham** [sonic-net/sonic-mgmt#15837]
### Issue Description

Happened when running snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py::test_pfc_pause_multi_lossless_prio_reboot[multidut_port_info0-cold] 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py", line 239, in test_pfc_pause_multi_lossless_prio_reboot
    run_pfc_test(api=snappi_api,
  File "/var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/snappi_tests/multidut/pfc/files/multidut_helper.py", line 239, in run_pfc_test
    tgen_flow_stats, switch_flow_stats, in_flight_flow_metrics = run_traffic(duthost=duthost,
  File "/var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/common/snappi_tests/traffic_generation.py", line 337, in run_traffic
    api.set_config(config)
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/snappi_api.py", line 216, in set_config
    raise SnappiIxnException(err)
snappi_ixnetwork.exceptions.SnappiIxnException:   File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/snappi_api.py", line 214, in set_config
    self.config_ixnetwork(config)
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/snappi_api.py", line 258, in config_ixnetwork
    self.vport.config()
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/vport.py", line 146, in config
    self._wait_for(lambda: self.is_protocols_stopped(),
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/vport.py", line 166, in _wait_for
    raise Exception(exp_msg)
 "Protocols are not stopped in 10 seconds
 ```
 
 
  
 
 ```
 30/11/2024 21:17:18 connectionpool._get_conn                 L0267 DEBUG  | Resetting dropped connection: 10.206.144.17
30/11/2024 21:17:18 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 207
30/11/2024 21:17:19 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 699
30/11/2024 21:17:19 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 597
30/11/2024 21:17:19 snappi_api.info                          L1132 INFO   | Config validation 0.038s
30/11/2024 21:17:19 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 859
30/11/2024 21:17:19 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "PATCH /api/v1/sessions/638/ixnetwork/traffic HTTP/1.1" 200 20
30/11/2024 21:17:19 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 162
30/11/2024 21:17:20 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/stopallprotocols HTTP/1.1" 202 114
30/11/2024 21:17:20 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 302
30/11/2024 21:17:20 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 280
30/11/2024 21:17:20 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:20 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 475
30/11/2024 21:17:20 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 402
30/11/2024 21:17:21 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 302
30/11/2024 21:17:21 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 280
30/11/2024 21:17:21 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:21 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 475
30/11/2024 21:17:21 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:23 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 302
30/11/2024 21:17:23 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 280
30/11/2024 21:17:24 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 403
30/11/2024 21:17:24 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 475
30/11/2024 21:17:24 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:25 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 302
30/11/2024 21:17:26 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 280
30/11/2024 21:17:26 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:26 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 475
30/11/2024 21:17:26 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:27 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 302
30/11/2024 21:17:27 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 280
30/11/2024 21:17:27 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:27 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 474
30/11/2024 21:17:27 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:28 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 302
30/11/2024 21:17:29 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 280
30/11/2024 21:17:29 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 401
30/11/2024 21:17:29 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 475
30/11/2024 21:17:29 connectionpool._make_request             L0429 DEBUG  | https://10.206.144.17:443 "POST /api/v1/sessions/638/ixnetwork/operations/select HTTP/1.1" 202 400
30/11/2024 21:17:29 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/snappi_api.py", line 214, in set_config
    self.config_ixnetwork(config)
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/snappi_api.py", line 258, in config_ixnetwork
    self.vport.config()
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/vport.py", line 146, in config
    self._wait_for(lambda: self.is_protocols_stopped(),
  File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/vport.py", line 166, in _wait_for
    raise Exception(exp_msg)
Exception: "Protocols are not stopped in 10 seconds
```

### Results you see

test failed because of  `Protocols are not stopped in 10 seconds` after calling  `api.set_config(config)`

### Results you expected to see

Should not have this error.

### Is it platform specific

generic

**Comment by sdszhang** [comment]
@kamalsahu0001 @selldinesh can you help to look into this issue? This is the first time we see it in our T2 testbed, but seems it has happened several times in the past on other testbeds too.

**Comment by kamalsahu0001** [comment]
Issue is not happening internally. Please collect diagnostic logs for that session, when the issue happens.

**Comment by sdszhang** [comment]
@kamalsahu0001 can you provide a screenshot for it? Thanks.

**Comment by YatishSVC** [comment]
@kamalsahu0001 Hi Kamal, 
We are seeing this issue again and is there a way to change the timeout?
@sdszhang @arlakshm for viz

**Comment by kamalsahu0001** [comment]
Can you please collect the diagnostics when the issue is reproduced.

You may add additional timeout in the script to see if it goes away.

Kamal

________________________________

**Comment by sdszhang** [comment]
after upgrading IXIA to 10.25, we are not seeing it in recent run. In monitoring.
