### ISSUE TITLE
BGP test_traffic_shift.py gets stuck 

### ISSUE THREAD

**Issue by AndriiLozovyi** [sonic-net/sonic-mgmt#5655]
**Description**
After [PR](https://github.com/Azure/sonic-mgmt/commit/2c623dbc1b9ffa2fec409891cbecb768cdd0cbca)  **bgp/test_traffic_shift.py** started to stuck, TC get stuck on **parse_routes_process** with below error: 

```{'msg': Traceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False}```

This error is spotted during executing in parallel on 32 VMs `parse_routes_process` function, error is seen on different VMs.  
No errors is spotted in the syslog. 
I added some logs for debug and this is what it looks like: 
```
16:03:51 test_traffic_shift.parse_routes_process  L0099 INFO   | {'msg': u'/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.exceptions import InvalidSignature\nTraceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False}; hostname=ARISTA05T2
16:03:51 test_traffic_shift.parse_routes_process  L0099 INFO   | {'msg': u'/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.exceptions import InvalidSignature\nTraceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False}; hostname=ARISTA13T0
16:03:51 test_traffic_shift.parse_routes_process  L0099 INFO   | {'msg': u'/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.exceptions import InvalidSignature\nTraceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False}; hostname=ARISTA04T0
16:03:51 test_traffic_shift.parse_routes_process  L0099 INFO   | {'msg': u'/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.exceptions import InvalidSignature\nTraceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False}; hostname=ARISTA13T2
16:03:51 test_traffic_shift.parse_routes_process  L0099 INFO   | {'msg': u'/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.exceptions import InvalidSignature\nTraceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False}; hostname=ARISTA14T0
```

When executing `bgp/test_traffic_shift.py` on previous commit - [PR](https://github.com/Azure/sonic-mgmt/commit/c56c85ce1ccffaaf9b87a064e15d67dea82aa4c9) test case is passing successfully and no error messages are spotted. 
**Steps to reproduce the issue:**
1. Run test bgp/test_traffic_shift.py
2.
3.

**Describe the results you received:**
It looks like some of the job's that was started in parallel are stuck due to connection error, this connection error was spotted on different random VMs during the test run. 

**Describe the results you expected:**
TC don't get stuck

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    SONiC Software Version: SONiC.master.94647-dirty-20220429.133828
    Distribution: Debian 11.3
    Kernel: 5.10.0-8-2-amd64
    Build commit: d258db8aa
    Build date: Fri Apr 29 19:07:06 UTC 2022
    Built by: AzDevOps@sonic-build-workers-001GZ0
    Platform: x86_64-arista_7170_64c
    HwSKU: Arista-7170-64C
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by AndriiLozovyi** [comment]
@congh-nvidia,
Could you please have a look ? 
Have you seen similar behavior?

**Comment by congh-nvidia** [comment]
> @congh-nvidia, Could you please have a look ? Have you seen similar behavior?
Hi @AndriiLozovyi ,
We don't observe similar issue in our tests. 
It seems the test failed when ansible was trying to execute commands on VMs to retrieve routes and some connections failed.
There's a difference that our testbed only has 4 VMs to check for the routes while there are 32 in your testbed. What I can guess is maybe there's some max connection limits in the sonic-mgmt docker?
Could you run this test on a testbed with fewer VMs or remove the parallel method but keep the checks to see if the test can pass?

**Comment by AndriiLozovyi** [comment]
@congh-nvidia,
The reason why there is **32 VMs**, it's because test case is run on **t1** topology, which is defined with 32 VMs. 
Below are the logs, when I removed parallel method and executed test case on **t1** topo: 
All test cases are passed and cmd is successfully run on each VM
```
12:18:55 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA16T2 time=2022-05-16 12:18:55.470334
12:18:59 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA16T0 time=2022-05-16 12:18:59.396162
12:19:03 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA11T0 time=2022-05-16 12:19:03.241808
12:19:07 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA10T0 time=2022-05-16 12:19:07.116403
12:19:11 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA11T2 time=2022-05-16 12:19:11.038726
12:19:14 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA10T2 time=2022-05-16 12:19:14.949722
12:19:18 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA09T2 time=2022-05-16 12:19:18.947834
12:19:22 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA09T0 time=2022-05-16 12:19:22.810263
12:19:26 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA06T0 time=2022-05-16 12:19:26.756315
12:19:30 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA06T2 time=2022-05-16 12:19:30.643961
12:19:34 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA08T2 time=2022-05-16 12:19:34.550487
12:19:38 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA08T0 time=2022-05-16 12:19:38.423871
12:19:42 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA07T0 time=2022-05-16 12:19:42.319403
12:19:46 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA07T2 time=2022-05-16 12:19:46.205705
12:19:50 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA01T2 time=2022-05-16 12:19:50.113792
12:19:53 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA01T0 time=2022-05-16 12:19:53.960873
12:19:57 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA05T2 time=2022-05-16 12:19:57.822303
12:20:01 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA05T0 time=2022-05-16 12:20:01.715299
12:20:05 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA02T0 time=2022-05-16 12:20:05.564963
12:20:09 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA03T0 time=2022-05-16 12:20:09.535993
12:20:13 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA02T2 time=2022-05-16 12:20:13.402112
12:20:17 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA03T2 time=2022-05-16 12:20:17.298061
12:20:21 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA04T2 time=2022-05-16 12:20:21.170700
12:20:25 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA04T0 time=2022-05-16 12:20:25.071097
12:20:29 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA15T0 time=2022-05-16 12:20:29.037750
12:20:32 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA15T2 time=2022-05-16 12:20:32.996655
12:20:36 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA14T0 time=2022-05-16 12:20:36.907055
12:20:40 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA14T2 time=2022-05-16 12:20:40.819272
12:20:44 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA12T2 time=2022-05-16 12:20:44.703675
12:20:48 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA12T0 time=2022-05-16 12:20:48.635278
12:20:52 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA13T2 time=2022-05-16 12:20:52.549338
12:20:56 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA13T0 time=2022-05-16 12:20:56.410156


12:21:06 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA16T2 time=2022-05-16 12:21:06.461204
12:21:13 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA16T0 time=2022-05-16 12:21:13.303866
12:21:20 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA11T0 time=2022-05-16 12:21:20.154632
12:21:27 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA10T0 time=2022-05-16 12:21:27.125379
12:21:33 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA11T2 time=2022-05-16 12:21:33.930681
12:21:40 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA10T2 time=2022-05-16 12:21:40.664524
12:21:47 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA09T2 time=2022-05-16 12:21:47.444079
12:21:54 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA09T0 time=2022-05-16 12:21:54.154687
12:22:00 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA06T0 time=2022-05-16 12:22:00.989625
12:22:07 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA06T2 time=2022-05-16 12:22:07.650556
12:22:14 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA08T2 time=2022-05-16 12:22:14.393286
12:22:21 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA08T0 time=2022-05-16 12:22:21.308242
12:22:28 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA07T0 time=2022-05-16 12:22:28.211538
12:22:34 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA07T2 time=2022-05-16 12:22:34.982682
12:22:42 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA01T2 time=2022-05-16 12:22:42.114061
12:22:49 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA01T0 time=2022-05-16 12:22:49.702608
12:22:56 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA05T2 time=2022-05-16 12:22:56.754575
12:23:03 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA05T0 time=2022-05-16 12:23:03.614635
12:23:10 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA02T0 time=2022-05-16 12:23:10.398332
12:23:17 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA03T0 time=2022-05-16 12:23:17.244977
12:23:24 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA02T2 time=2022-05-16 12:23:24.114984
12:23:30 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA03T2 time=2022-05-16 12:23:30.986790
12:23:37 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA04T2 time=2022-05-16 12:23:37.762169
12:23:44 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA04T0 time=2022-05-16 12:23:44.721892
12:23:51 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA15T0 time=2022-05-16 12:23:51.643760
12:23:58 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA15T2 time=2022-05-16 12:23:58.487772
12:24:05 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA14T0 time=2022-05-16 12:24:05.416516
12:24:12 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA14T2 time=2022-05-16 12:24:12.281462
12:24:19 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA12T2 time=2022-05-16 12:24:19.066306
12:24:25 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA12T0 time=2022-05-16 12:24:25.884313
12:24:32 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA13T2 time=2022-05-16 12:24:32.680682
12:24:39 test_traffic_shift.parse_routes_on_eos   L0082 INFO   | cmd_failed=False; hostname=ARISTA13T0 time=2022-05-16 12:24:39.621638
PASSED
```

But even when I execute test case on **t0** topology, which have **4 VMs**, with parallel method, I still see this error and that test case gets stuck: 

```
----------------------------------------------------------------------------- live log call ----------------------------------------------------------------------------- 
16:03:24 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA04T1 time=2022-05-16 16:03:24.755192
16:03:24 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA02T1 time=2022-05-16 16:03:24.759371
16:03:24 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA03T1 time=2022-05-16 16:03:24.774535
16:03:24 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA01T1 time=2022-05-16 16:03:24.839682
16:03:24 test_traffic_shift.verify_all_routes_ann L0135 INFO   | Verifying all routes(ipv4) are announced to ARISTA04T1
16:03:24 test_traffic_shift.verify_all_routes_ann L0135 INFO   | Verifying all routes(ipv4) are announced to ARISTA03T1
16:03:24 test_traffic_shift.verify_all_routes_ann L0135 INFO   | Verifying all routes(ipv4) are announced to ARISTA02T1
16:03:24 test_traffic_shift.verify_all_routes_ann L0135 INFO   | Verifying all routes(ipv4) are announced to ARISTA01T1
16:03:44 test_traffic_shift.verify_all_routes_ann L0131 INFO   | Verifying all routes(ipv6) are announced to bgp neighbors
16:03:52 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA04T1 time=2022-05-16 16:03:52.037915
16:03:52 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA02T1 time=2022-05-16 16:03:52.250275
16:03:52 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=True; hostname=ARISTA01T1 time=2022-05-16 16:03:52.322813
16:03:52 test_traffic_shift.parse_routes_process  L0100 INFO   | {'msg': u'/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.exceptions import InvalidSignature\nTraceback (most recent call last):\n  File "/usr/local/bin/ansible-connection", line 335, in <module>\n    main()\n  File "/usr/local/bin/ansible-connection", line 299, in main\n    conn.set_options(var_options=variables)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 180, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 151, in _exec_jsonrpc\n    out = self.send(data)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/connection.py", line 200, in send\n    raise ConnectionError(\'unable to connect to socket\', err=to_text(e, errors=\'surrogate_then_replace\'), exception=traceback.format_exc())\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n', 'failed': True, '_ansible_no_log': False} hostname=ARISTA01T1 2022-05-16 16:03:52.323756
16:03:52 test_traffic_shift.parse_routes_process  L0098 INFO   | cmd_failed=False; hostname=ARISTA03T1 time=2022-05-16 16:03:52.430111
```

**Comment by congh-nvidia** [comment]
@AndriiLozovyi I've double checked our test results, we also have t1 topology with 32 VMs, and the test passed.
It looks like an environment issue to me, can you check your ansible version?  We are using 2.8.12.
root@2148e96f57ae:/devts# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
abstract-open-traffic-generator (0.0.68)
adal (1.2.7)
allure-pytest (2.8.22)
allure-python-commons (2.8.22)
**ansible (2.8.12)**

**Comment by AndriiLozovyi** [comment]
@congh-nvidia, 
Environment looks identical, our **python is 2.7.17**

AzDevOps@65cd1eb84b42:$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
abstract-open-traffic-generator (0.0.68)
adal (1.2.7)
allure-pytest (2.8.22)
allure-python-commons (2.8.22)
**ansible (2.8.12)**

**Comment by congh-nvidia** [comment]
@AndriiLozovyi I don't know what's the root cause of the failure on your testbed. It looks removing the parallel method will solve the problem, but also increase the running time of the test.
Could you further investigate what caused the connection errors on your testbed?
Thanks.

**Comment by AndriiLozovyi** [comment]
Closing this issue as it is fixed by these PRs - [6276](https://github.com/sonic-net/sonic-mgmt/pull/6276), [6263](https://github.com/sonic-net/sonic-mgmt/pull/6263)
