### ISSUE TITLE
Get the following error involved by PR: https://github.com/Azure/sonic-mgmt/pull/5530

### ISSUE THREAD

**Issue by Pterosaur** [sonic-net/sonic-mgmt#5728]
https://github.com/Azure/sonic-mgmt/blob/56a6217070bbd8c779ba98cd57d509ebebca1de1/tests/macsec/macsec_platform_helper.py#L62

```
28/05/2022 00:42:00 utilities.wait_until                     L0113 ERROR  | Exception caught while checking _test_mka_session:Traceback (most recent call last):
  File "/var/src/s/tests/common/utilities.py", line 107, in wait_until
    check_result = condition(*args, **kwargs)
  File "/var/src/s/tests/macsec/test_macsec.py", line 61, in _test_mka_session
    dut_macsec_port = get_macsec_ifname(duthost, port_name)
  File "/var/src/s/tests/macsec/macsec_platform_helper.py", line 75, in get_macsec_ifname
    asic = host.get_port_asic_instance(intf)
NameError: global name 'intf' is not defined
, error:global name 'intf' is not defined
```

**Comment by Pterosaur** [comment]
This commit is a proposal for fixing this issue: https://github.com/Azure/sonic-mgmt/pull/5618/commits/557105cef378967b7b01eead48aae3070b257250
