### ISSUE TITLE
[pr check] check_dut_health fail and issued reboot, reboot fail to find asic on internal port

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-mgmt#6328]
**Description**

**Steps to reproduce the issue:**
issue is not reproducible, seen on multi-asic pr check

**Describe the results you received:**
tacacs/test_rw_user.py::test_rw_user[vlab-08] 
-------------------------------- live log setup --------------------------------
23:11:28 recover.recover                          L0092 WARNING| Try to recover vlab-08 using method adaptive
23:11:28 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel04
23:11:28 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel20
23:11:28 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel50
23:11:28 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel49
23:11:28 recover.__recover_interfaces             L0032 WARNING| Restoring port: Ethernet-BP72
ERROR                                                                    [ 50%]Loading callback
.....
common/plugins/sanity_check/recover.py:98: in recover
    adaptive_recover(dut, localhost, fanouthosts, check_results, wait_time)
common/plugins/sanity_check/recover.py:65: in adaptive_recover
    action = __recover_interfaces(dut, fanouthosts, result, wait_time)
common/plugins/sanity_check/recover.py:42: in __recover_interfaces
    asic = dut.get_port_asic_instance(port)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <MultiAsicSonicHost vlab-08>, port = 'Ethernet-BP72'

    def get_port_asic_instance(self, port):
        """
        Returns the ASIC instance to which the port belongs
        Args:
            port: Port ID
    
        Returns:
            returns the ASIC instance if found, else None
        """
        for asic in self.asics:
            if asic.port_exists(port):
                return asic
    
        pytest_assert(
            False,
>           "ASIC instance not found for port {}".format(port)
        )
E       Failed: ASIC instance not found for port Ethernet-BP72

asic       = <SonicAsic 3>
port       = 'Ethernet-BP72'
self       = <MultiAsicSonicHost vlab-08>

common/devices/multi_asic.py:365: Failed

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wenyiz2021** [comment]
1. why reboot happened?

- check_interfaces_on_dut failed:
`09/09/2022 10:20:14 checks._check_interfaces_on_dut          L0130 INFO   | Done checking interfaces status on vlab-08
09/09/2022 10:20:14 parallel.on_terminate                    L0081 INFO   | process _check_interfaces_on_dut--<MultiAsicSonicHost vlab-08> terminated with exit code None
09/09/2022 10:20:14 parallel.parallel_run                    L0149 DEBUG  | task completed 1, running 0
09/09/2022 10:20:14 parallel.parallel_run                    L0204 INFO   | Completed running processes for target "_check_interfaces_on_dut" in 0:00:41.179675 seconds
09/09/2022 10:20:14 __init__.do_checks                       L0103 DEBUG  | check results of each item [{'check_item': 'interfaces', 'failed': True, 'host': 'vlab-08', 'down_ports': [u'PortChannel04', u'PortChannel20', u'PortChannel50', u'PortChannel49', u'Ethernet-BP72', u'Ethernet-BP64', u'Ethernet-BP76', u'Ethernet-BP68']}]`

- While on each asic, all interfaces are up:
`09/09/2022 10:20:11 base._run                                L0082 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_ip_interface#150: [vlab-08] AnsibleModule::show_ip_interface Result => {"invocation": {"module_args": {"namespace": "asic3"}}, **"failed": false,** "changed": false, "_ansible_no_log": false, "ansible_facts": {"ip_interfaces": {"Loopback4096": {"bgp_neighbor": "N/A", "ipv4": "8.0.0.3", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "32"}, "docker0": {"bgp_neighbor": "N/A", "ipv4": "240.127.1.1", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "24"}, "Loopback0": {"bgp_neighbor": "N/A", "ipv4": "10.1.0.32", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "32"}, "PortChannel49": {"bgp_neighbor": "N/A", "ipv4": "10.1.0.2", "peer_ipv4": "N/A", "admin": "up", "oper_state": "down", "prefix_len": "31"}, "PortChannel50": {"bgp_neighbor": "N/A", "ipv4": "10.1.0.6", "peer_ipv4": "N/A", "admin": "up", "oper_state": "down", "prefix_len": "31"}, "lo": {"bgp_neighbor": "N/A", "ipv4": "127.0.0.1", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "8"}, "eth0": {"bgp_neighbor": "N/A", "ipv4": "240.127.1.2", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "24"}}}}
09/09/2022 10:20:11 base._run                                L0063 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_interface#137: [vlab-08] AnsibleModule::show_interface, args=[], kwargs={"include_internal_intfs": true, **"namespace": "asic3"**, "command": "status"}
09/09/2022 10:20:14 base._run                                L0082 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_interface#137: [vlab-08] AnsibleModule::show_interface Result => {"invocation": {"module_args": {"include_internal_intfs": true, "interfaces": null, "namespace": "asic3", "command": "status", "up_ports": {}}}, **"failed": false,** "changed": false, "_ansible_no_log": false, "ansible_facts": {"ansible_interface_link_down_ports": [], "int_status": {}}}`

**Comment by wenyiz2021** [comment]
also seen on external ports:

tacacs/test_rw_user.py::test_rw_user[vlab-08] 
-------------------------------- live log setup --------------------------------
09:40:19 recover.recover                          L0092 WARNING| Try to recover vlab-08 using method adaptive
09:40:19 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel03
09:40:19 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel102
09:40:19 recover.__recover_interfaces             L0032 WARNING| Restoring port: PortChannel04
09:40:19 recover.__recover_interfaces             L0032 WARNING| Restoring port: Ethernet0
    def get_port_asic_instance(self, port):
        """
        Returns the ASIC instance to which the port belongs
        Args:
            port: Port ID
    
        Returns:
            returns the ASIC instance if found, else None
        """
        for asic in self.asics:
            if asic.port_exists(port):
                return asic
    
        pytest_assert(
            False,
>           "ASIC instance not found for port {}".format(port)
        )
E       Failed: ASIC instance not found for port Ethernet0

asic       = <SonicAsic 3>
port       = 'Ethernet0'
self       = <MultiAsicSonicHost vlab-08>

common/devices/multi_asic.py:365: Failed
- generated xml file: /var/src/s/tests/logs/multi_asic_t1_lag/tacacs/test_rw_user.xml -

**Comment by wenyiz2021** [comment]
2 triggers of recover for now:

1.
```   09:21:57 conftest.check_dut_health_status         L1756 WARNING| Check Dut health failed: Dut health check results {"core_dump_check": {"new_core_dumps": {"vlab-08": []}, "pass": true}, "config_db_check": {"cur_only_config": {"vlab-08": {}}, "inconsistent_config": {"vlab-08": {"TACPLUS_SERVER": {"pre_value": {"10.0.0.9": {"priority": "1", "tcp_port": "49"}, "10.0.0.8": {"priority": "1", "tcp_port": "49"}}, "cur_value": {"fec0::ffff:afa:a": {"priority": "1", "tcp_port": "49"}, "10.0.0.9": {"priority": "1", "tcp_port": "49"}, "10.0.0.8": {"priority": "1", "tcp_port": "49"}}}}}, "pre_only_config": {"vlab-08": {}}, "pass": false}}, running module test_ro_user.py


- generated xml file: /var/src/s/tests/logs/multi_asic_t1_lag/tacacs/test_ro_user.xml -
========================= 4 passed in 1745.39 seconds ==========================
INFO:root:Can not get Allure report URL. Please check logs
Running: pytest tacacs/test_rw_user.py --inventory ../ansible/veos_vtb --host-pattern vlab-08 --testbed vms-kvm-four-asic-t1-lag --testbed_file vtestbed.yaml --log-cli-level warning --log-file-level debug --kube_master unset --showlocals --assert plain --show-capture no -rav --ignore=ptftests --ignore=acstests --ignore=saitests --ignore=scripts --ignore=k8s --ignore=sai_qualify --maxfail=1 --log-file logs/multi_asic_t1_lag/tacacs/test_rw_user.log --junitxml=logs/multi_asic_t1_lag/tacacs/test_rw_user.xml --allow_recover --completeness_level=confident
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.11.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /var/src/s/tests, inifile: pytest.ini
plugins: metadata-1.11.0, repeat-0.9.1, allure-pytest-2.8.22, xdist-1.28.0, html-1.22.1, forked-1.3.0, celery-4.4.7, ansible-2.2.2
collected 2 items

tacacs/test_rw_user.py::test_rw_user[vlab-08] 
-------------------------------- live log setup --------------------------------
09:29:00 utilities.wait_until                     L0116 ERROR  | Exception caught while checking _check_bgp_status_helper:Traceback (most recent call last):
  File "/var/src/s/tests/common/utilities.py", line 110, in wait_until
    check_result = condition(*args, **kwargs)
  File "/var/src/s/tests/common/plugins/sanity_check/checks.py", line 150, in _check_bgp_status_helper
    bgp_facts = dut.bgp_facts(asic_index='all')
  File "/var/src/s/tests/common/devices/multi_asic.py", line 112, in _run_on_asics
    return [getattr(asic, self.multi_asic_attr)(*module_args, **asic_complex_args) for asic in self.asics]
  File "/var/src/s/tests/common/devices/sonic_asic.py", line 106, in bgp_facts
    return self.sonichost.bgp_facts(*module_args, **complex_args)
  File "/var/src/s/tests/common/devices/base.py", line 89, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
RunAnsibleModuleFail: run module bgp_facts failed, Ansible Results =>
{
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "instance_id": 3, 
            "num_npus": 1
        }
    }, 
    "msg": "Command failed rc=1, out=, err=Error response from daemon: Container 1f52441cd8cfd642379085df9435db9584169978dfe67b0f55afff3b43a839ae is not running\n"
}
, error:run module bgp_facts failed, Ansible Results =>
```

2.  check_dut_health failed:
```
tacacs/test_ro_user.py::test_ro_user_banned_command[vlab-08] PASSED      [100%]
------------------------------ live log teardown -------------------------------
09:32:52 conftest.check_dut_health_status         L1756 WARNING| Check Dut health failed: Dut health check results {"core_dump_check": {"new_core_dumps": {"vlab-08": []}, "pass": true}, "config_db_check": {"cur_only_config": {"vlab-08": {}}, "inconsistent_config": {"vlab-08": {"TACPLUS_SERVER": {"pre_value": {"10.0.0.9": {"priority": "1", "tcp_port": "49"}, "10.0.0.8": {"priority": "1", "tcp_port": "49"}}, "cur_value": {"fec0::ffff:afa:a": {"priority": "1", "tcp_port": "49"}, "10.0.0.9": {"priority": "1", "tcp_port": "49"}, "10.0.0.8": {"priority": "1", "tcp_port": "49"}}}}}, "pre_only_config": {"vlab-08": {}}, "pass": false}}, running module test_ro_user.py

```

**Comment by wenyiz2021** [comment]
issue also seen on dualtor PR check
