### ISSUE TITLE
A bunch of platform_tests.api test cases failed due to the closed connection with server

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#6512]
**Description**

many platform_tests.api test cases failed because the closed connection with server, please see the error message below, failure reason is `BadStatusLine: No status line received - the server has closed the connection` 
it's a known Celestica issue, file an issue here to xfail these test cases for now. 
Will remove xfail when this issue is resolved.
```
platform_tests/api/test_chassis.py::TestChassisApi::test_get_name[str-dx010-acs-4] PASSED [ 4%] 
platform_tests/api/test_chassis.py::TestChassisApi::test_get_presence[str-dx010-acs-4] PASSED [ 8%] 
platform_tests/api/test_chassis.py::TestChassisApi::test_get_model[str-dx010-acs-4] 
-------------------------------- live log call --------------------------------- 
11:46:31 __init__.pytest_runtest_call L0040 ERROR | Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest 
self.ihook.pytest_pyfunc_call(pyfuncitem=self) 
File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__ 
return self._hookexec(self, self.get_hookimpls(), kwargs) 
File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec 
return self._inner_hookexec(hook, methods, kwargs) 
File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda> 
firstresult=hook.spec.opts.get("firstresult") if hook.spec else False, 
File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall 
return outcome.get_result() 
File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result 
_reraise(*ex) # noqa 
File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall 
res = hook_impl.function(*args) 
File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call 
testfunction(**testargs) 
File "/azp/agent/_work/70/s/tests/platform_tests/api/test_chassis.py", line 139, in test_get_model 
model = chassis.get_model(platform_api_conn) 
File "/azp/agent/_work/70/s/tests/common/helpers/platform_api/chassis.py", line 35, in get_model 
return chassis_api(conn, 'get_model') 
File "/azp/agent/_work/70/s/tests/common/helpers/platform_api/chassis.py", line 16, in chassis_api 
resp = conn.getresponse() 
File "/usr/lib/python2.7/httplib.py", line 1178, in getresponse 
response.begin() 
File "/usr/lib/python2.7/httplib.py", line 452, in begin 
version, status, reason = self._read_status() 
File "/usr/lib/python2.7/httplib.py", line 416, in _read_status 
raise BadStatusLine("No status line received - the server has closed the connection") 
BadStatusLine: No status line received - the server has closed the connection 
```

**Steps to reproduce the issue:**
1. Run platform_tests/api/test_chassis.py::TestChassisApi::test_get_name
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
test_get_model is passing consistently.
