### ISSUE TITLE
[tests/ecmp/inner_hashing] and [tests/ecmp] test failure

### ISSUE THREAD

**Issue by lipxu** [sonic-net/sonic-mgmt#6558]
**Description**
[tests/ecmp] test failure log
12/10/2022 11:29:14 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/azp/agent/_work/4/s/sonic-mgmt-int/tests/ecmp/test_fgnhg.py", line 614, in test_fg_ecmp
    fg_ecmp_to_regular_ecmp_transitions(ptfhost, duthost, router_mac, net_ports, port_list, ipv4_to_port, bank_0_port, bank_1_port, PREFIX_IPV4_LIST, cfg_facts)
  File "/azp/agent/_work/4/s/sonic-mgmt-int/tests/ecmp/test_fgnhg.py", line 571, in fg_ecmp_to_regular_ecmp_transitions
    partial_ptf_runner(ptfhost, 'create_flows', dst_ip, exp_flow_count)
  File "/azp/agent/_work/4/s/sonic-mgmt-int/tests/ecmp/test_fgnhg.py", line 225, in partial_ptf_runner
    log_file=log_file)
  File "/azp/agent/_work/4/s/sonic-mgmt-int/tests/ptf_runner.py", line 55, in ptf_runner
    raise Exception
Exception

"AssertionError: Received expected packet on port 30 for device 0, but it should have arrived on one of these ports: [1, 2, 7, 20, 21, 22, 23, 24]."

similar log with [tests/ecmp/inner_hashing]

**Steps to reproduce the issue:**
1. run the failure test
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by Blueve** [comment]
Sounds like cause by wrong routes announcement, potential cases:
1. Announced routes conflicts with local direct routes
2. Announced routes in test conflicts with IP range that has been used in announce_route

**Comment by liat-grozovik** [comment]
@yxieca can you please add it to the test triage meeting?

**Comment by yxieca** [comment]
Tests are passing consistently now.

**Comment by ashutosh-agrawal** [comment]
@yxieca I'm running this test on a Cisco platform and see the same failure. Any idea what was fixed for this test to start passing?
