### ISSUE TITLE
[everflow] [masic] [20191130.87] [image issue] test_everflow_per_interface fail to send/receive any packet on ports

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-mgmt#6920]
**Description**
12/11/2022 12:03:24 test_everflow_per_interface.test_everflo L0184 INFO   | Verifying packet ingress from Ethernet180 is mirrored
12/11/2022 12:03:24 testutils.verify_packet_any_port         L2523 DEBUG  | Checking for pkt on device 0, port [0, 1, 4, 20, 21, 16, 5, 17]
12/11/2022 12:03:29 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/azp/agent/_work/9/s/sonic-mgmt-int/tests/everflow/test_everflow_per_interface.py", line 185, in test_everflow_per_interface
    send_and_verify_packet(ptfadapter, packet, exp_packet, ptf_idx, uplink_ports, True)
  File "/azp/agent/_work/9/s/sonic-mgmt-int/tests/everflow/test_everflow_per_interface.py", line 170, in send_and_verify_packet
    testutils.verify_packet_any_port(ptfadapter, pkt=expected_packet, ports=rx_ports, timeout=5)
  File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 2538, in verify_packet_any_port
    % (ports, device_number, result.format()))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Did not receive expected packet on any of ports [0, 1, 4, 20, 21, 16, 5, 17] for device 0.

09/30/2022 `with same image version` test result was good:
00:01:22 test_everflow_per_interface.test_everflo L0184 INFO   | Verifying packet ingress from Ethernet180 is mirrored
00:01:22 test_everflow_per_interface.test_everflo L0184 INFO   | Verifying packet ingress from Ethernet136 is mirrored
00:01:22 test_everflow_per_interface.test_everflo L0184 INFO   | Verifying packet ingress from Ethernet184 is mirrored
00:01:22 test_everflow_per_interface.test_everflo L0184 INFO   | Verifying packet ingress from Ethernet188 is mirrored
00:01:22 test_everflow_per_interface.test_everflo L0189 INFO   | Verifying packet ingress from Ethernet0 is not mirrored
00:01:22 test_everflow_per_interface.test_everflo L0189 INFO   | Verifying packet ingress from Ethernet244 is not mirrored
00:01:23 test_everflow_per_interface.test_everflo L0189 INFO   | Verifying packet ingress from Ethernet248 is not mirrored
00:01:24 test_everflow_per_interface.test_everflo L0189 INFO   | Verifying packet ingress from Ethernet4 is not mirrored
PASSED      

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wenyiz2021** [comment]
closed as manual rerun passed, image version 20191130.78, test branch 202012:
everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv4] PASSED                                                                                                                                                                   [ 50%]
everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv6] PASSED                                                                                                                                                                   [100%]

==================================================================================================================== warnings summary =====================================================================================================================
everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv4]
everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv6]
  /usr/local/lib/python2.7/dist-packages/scapy/packet.py:397: DeprecationWarning: seqence_number has been deprecated in favor of sequence_number since 2.4.4 !
    ), DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
----------------------------------------------------------------------------------------------- generated xml file: /data/sonic-mgmt-int/tests/logs/tr.xml ------------------------------------------------------------------------------------------------
========================================================================================================== 2 passed, 2 warnings in 75.21 seconds =========================================================================================================

**Comment by wenyiz2021** [comment]
reopen as 20191130.87 image see this issue, .78 does not

**Comment by wenyiz2021** [comment]
everflow/test_everflow_per_interface.py:170: in send_and_verify_packet
    testutils.verify_packet_any_port(ptfadapter, pkt=expected_packet, ports=rx_ports, timeout=5)
/usr/lib/python2.7/dist-packages/ptf/testutils.py:2538: in verify_packet_any_port
    % (ports, device_number, result.format()))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>
msg = 'Did not receive expected packet on any of ports [0, 1, 20, 21, 16, 5, 4, 17] for device 0.\n========== EXPECTED =====...  00 00 00 00 00 00 00 00  00 00\n\n========== RECEIVED ==========\n0 total packets.\n==============================\n'

    def fail(self, msg=None):
        """Fail immediately, with the given message."""
>       raise self.failureException(msg)
E       AssertionError: Did not receive expected packet on any of ports [0, 1, 20, 21, 16, 5, 4, 17] for device 0.
E       ========== EXPECTED ==========
E       Mask:
E       0000  00 01 02 03 04 05 00 BE 75 3A EF 50 08 00 45 20  ........u:.P..E 
E       0010  00 7C 00 00 00 00 04 2F B0 2E 01 01 01 01 02 02  .|...../........
E       0020  02 02 00 00 88 BE 00 BE 75 3A EF 50 DE 60 05 DC  ........u:.P.`..
E       0030  3A 00 08 00 45 00 00 56 00 01 00 00 40 06 F9 4D  :...E..V....@..M
E       0040  C0 A8 00 01 C0 A8 00 02 04 D2 00 50 00 00 00 00  ...........P....
E       0050  00 00 00 00 50 02 20 00 1C 75 00 00 74 65 73 74  ....P. ..u..test
E       0060  73 2E 65 76 65 72 66 6C 6F 77 2E 74 65 73 74 5F  s.everflow.test_
E       0070  65 76 65 72 66 6C 6F 77 5F 70 65 72 5F 69 6E 74  everflow_per_int
E       0080  65 72 66 61 63 65 20 74 65 73                    erface tes
E       mask = 00 00 00 00 00 00 ff ff  ff ff ff ff ff ff f0 00
E       0010   00 00 ff ff 1f ff 00 ff  00 00 ff ff ff ff ff ff
E       0020   ff ff ff ff ff ff 00 00  00 00 00 00 00 00 00 00
E       0030   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
E       0040   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
E       0050   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
E       0060   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
E       0070   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
E       0080   00 00 00 00 00 00 00 00  00 00
E       
E       ========== RECEIVED ==========
E       0 total packets.
E       ==============================

msg        = 'Did not receive expected packet on any of ports [0, 1, 20, 21, 16, 5, 4, 17] for device 0.\n========== EXPECTED =====...  00 00 00 00 00 00 00 00  00 00\n\n========== RECEIVED ==========\n0 total packets.\n==============================\n'
self       = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>

/usr/lib/python2.7/unittest/case.py:410: AssertionError
