### ISSUE TITLE
[202012] Some testcases throw `KeyError` while retrieve fanout information from fixture `fanouthosts`

### ISSUE THREAD

**Issue by lizhijianrd** [sonic-net/sonic-mgmt#7408]
**Description**

On 202012 branch, some testcases throw `KeyError` while retrieve fanout information from fixture `fanouthosts`.

Here is a sample error occurred on `test_lag`:

```
pc/test_lag_2.py::test_lag[nokia-7215|PortChannel103-single_lag] 
-------------------------------- live log call ---------------------------------
19:26:44 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/azp/_work/25/s/sonic-mgmt-int/tests/pc/test_lag_2.py", line 302, in test_lag
    test_instance.run_single_lag_test(lag_name, lag_facts)
  File "/azp/_work/25/s/sonic-mgmt-int/tests/pc/test_lag_2.py", line 205, in run_single_lag_test
    self.__verify_lag_minlink(self.fanouthosts[peer_device], lag_name, lag_facts, neighbor_intf, deselect_time=5)
KeyError: u'arista-7260cx3-fan-13'
```

**Comment by lizhijianrd** [comment]
Fixed by #7409
