### ISSUE TITLE
test_gnmi_configdb.py fails and block sanity check

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#7462]
**Description**

The failed reason is as below:
```
2023-01-23T21:48:43.3970447Z gnmi/test_gnmi_configdb.py::test_gnmi_configdb_incremental_01 
2023-01-23T21:48:43.3977200Z -------------------------------- live log call ---------------------------------
2023-01-23T21:48:43.3979950Z 21:48:43 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
2023-01-23T21:48:43.3983142Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
2023-01-23T21:48:43.3985333Z     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
2023-01-23T21:48:43.3988037Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
2023-01-23T21:48:43.3990294Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2023-01-23T21:48:43.3993103Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
2023-01-23T21:48:43.3995348Z     return self._inner_hookexec(hook, methods, kwargs)
2023-01-23T21:48:43.3998695Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
2023-01-23T21:48:43.4001087Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2023-01-23T21:48:43.4004049Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
2023-01-23T21:48:43.4006044Z     return outcome.get_result()
2023-01-23T21:48:43.4008469Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
2023-01-23T21:48:43.4011422Z     _reraise(*ex)  # noqa
2023-01-23T21:48:43.4014629Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
2023-01-23T21:48:43.4016602Z     res = hook_impl.function(*args)
2023-01-23T21:48:43.4019354Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
2023-01-23T21:48:43.4021717Z     testfunction(**testargs)
2023-01-23T21:48:43.4023924Z   File "/azp/_work/19/s/tests/gnmi/test_gnmi_configdb.py", line 63, in test_gnmi_configdb_incremental_01
2023-01-23T21:48:43.4026152Z     assert interface is not None, "Invalid interface"
2023-01-23T21:48:43.4027828Z AssertionError: Invalid interface
2023-01-23T21:48:43.4028523Z 
```

**Steps to reproduce the issue:**
1. run gnmi/test_gnmi_configdb.py
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@qiluo-msft can you assign someone to work on this issue?
