### ISSUE TITLE
Error collecting test_ssh_ciphers.py

### ISSUE THREAD

**Issue by wangxin** [sonic-net/sonic-mgmt#7854]
**Description**

Run test_ssh_ciphers.py got collection error like below:

```
2023-03-24T21:53:56.9749451Z ==================================== ERRORS ====================================
2023-03-24T21:53:56.9754261Z ___________________ ERROR collecting ssh/test_ssh_ciphers.py ___________________
2023-03-24T21:53:56.9759885Z /usr/local/lib/python2.7/dist-packages/pluggy/hooks.py:286: in __call__
2023-03-24T21:53:56.9764215Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2023-03-24T21:53:56.9769172Z /usr/local/lib/python2.7/dist-packages/pluggy/manager.py:93: in _hookexec
2023-03-24T21:53:56.9773624Z     return self._inner_hookexec(hook, methods, kwargs)
2023-03-24T21:53:56.9778342Z /usr/local/lib/python2.7/dist-packages/pluggy/manager.py:87: in <lambda>
2023-03-24T21:53:56.9782776Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2023-03-24T21:53:56.9788105Z /usr/local/lib/python2.7/dist-packages/_pytest/python.py:234: in pytest_pycollect_makeitem
2023-03-24T21:53:56.9792419Z     res = list(collector._genfunctions(name, obj))
2023-03-24T21:53:56.9797678Z /usr/local/lib/python2.7/dist-packages/_pytest/python.py:410: in _genfunctions
2023-03-24T21:53:56.9801997Z     self.ihook.pytest_generate_tests(metafunc=metafunc)
2023-03-24T21:53:56.9806706Z /usr/local/lib/python2.7/dist-packages/pluggy/hooks.py:286: in __call__
2023-03-24T21:53:56.9810951Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2023-03-24T21:53:56.9815968Z /usr/local/lib/python2.7/dist-packages/pluggy/manager.py:93: in _hookexec
2023-03-24T21:53:56.9820447Z     return self._inner_hookexec(hook, methods, kwargs)
2023-03-24T21:53:56.9825159Z /usr/local/lib/python2.7/dist-packages/pluggy/manager.py:87: in <lambda>
2023-03-24T21:53:56.9829544Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2023-03-24T21:53:56.9833635Z ssh/conftest.py:72: in pytest_generate_tests
2023-03-24T21:53:56.9838348Z     metafunc.parametrize('enum_dut_ssh_kex', generate_ssh_ciphers(metafunc, "kex"))
2023-03-24T21:53:56.9843351Z /usr/local/lib/python2.7/dist-packages/_pytest/python.py:1004: in parametrize
2023-03-24T21:53:56.9847531Z     function_definition=self.definition,
2023-03-24T21:53:56.9852324Z /usr/local/lib/python2.7/dist-packages/_pytest/mark/structures.py:125: in _for_parametrize
2023-03-24T21:53:56.9857074Z     parameters = cls._parse_parametrize_parameters(argvalues, force_tuple)
2023-03-24T21:53:56.9862564Z /usr/local/lib/python2.7/dist-packages/_pytest/mark/structures.py:119: in _parse_parametrize_parameters
2023-03-24T21:53:56.9867298Z     ParameterSet.extract_from(x, force_tuple=force_tuple) for x in argvalues
2023-03-24T21:53:56.9871900Z E   TypeError: 'NoneType' object is not iterable
2023-03-24T21:53:56.9876826Z - generated xml file: /azp/_work/19/s/sonic-mgmt-int/tests/logs/ssh/test_ssh_ciphers.xml -
2023-03-24T21:53:56.9880952Z Traceback (most recent call last):
2023-03-24T21:53:56.9884659Z   File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit
2023-03-24T21:53:56.9888556Z     stream.write(fs % msg)
2023-03-24T21:53:56.9893206Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/capture.py", line 441, in write
2023-03-24T21:53:56.9895560Z     self.buffer.write(obj)
2023-03-24T21:53:56.9897032Z ValueError: I/O operation on closed file
2023-03-24T21:53:56.9898312Z Logged from file __init__.py, line 64
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
This test case is part of our PR test. Not sure why PR tests are passing?

**Comment by wangxin** [comment]
This issue was fixed in https://github.com/sonic-net/sonic-mgmt/pull/8388
