### ISSUE TITLE
Getting AttributeError: Mask instance has no attribute 'set_do_not_care_packet' error while running acl test suite

### ISSUE THREAD

**Issue by rajneeshaec** [sonic-net/sonic-mgmt#8003]
**Problem Summary:-**  Acl test suite is failing because of below errors.

**Steps to reproduce the issue:**
run acl test suite

**Error logs:-**
08:19:19 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/var/AzDevOps/sonic-mgmt/tests/acl/test_acl.py", line 1002, in test_l4_dport_match_forwarded
    self._verify_acl_traffic(setup, direction, ptfadapter, pkt, False, ip_version)
  File "/var/AzDevOps/sonic-mgmt/tests/acl/test_acl.py", line 1091, in _verify_acl_traffic
    exp_pkt = self.expected_mask_routed_packet(pkt, ip_version)
  File "/var/AzDevOps/sonic-mgmt/tests/acl/test_acl.py", line 863, in expected_mask_routed_packet
    exp_pkt.set_do_not_care_packet(packet.Ether, "dst")
**AttributeError: Mask instance has no attribute 'set_do_not_care_packet'**

**Comment by bingwang-ms** [comment]
May I know on which branch did you see this error? I'm not aware of any issue in `test_acl.py`.

**Comment by rajneeshaec** [comment]
Hi @bingwang-ms 

  I am running from master branch. Please find details given below:-
  
   AzDevOps@bb0462e68d7f:~/sonic-mgmt$ git branch
* master
AzDevOps@bb0462e68d7f:~/sonic-mgmt$ git log
commit 34ce7e3c2cec20a7619af5b005dea21282bed8ef (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel Lin <127807777+msftdaniellin@users.noreply.github.com>
Date:   Tue Apr 4 01:36:35 2023 -0700

    Add check to see if it's vendor test to improve wan test (#7844)

Thanks
Rajneesh

**Comment by wangxin** [comment]
+ @wsycqyz This issue is caused by the python3 migration change #7748 

In python2, ptf version is 0.9.1.
In python3, ptf version is 0.9.3.

Bound method `set_do_not_care_packet` for a Mask object is only available in ptf 0.9.3.

Probably need to use different method based on ptf version.

@rajneeshaec, can you try to activate the python3 virtual environment and use python3 to run this test?
