### ISSUE TITLE
generic_config_updater/test_eth_interface.py failed

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#8143]
**Description**

1.	Error log 1 for test_eth_interface_admin_change on latest 202205 image.
```
E Match Messages:
E Apr 21 10:25:39.356657 str-7260cx3-acs-7 ERR syncd#syncd: [none] SAI_API_BUFFER:brcm_sai_remove_buffer_profile:2529 Profile 0x190000000a is in use by port 34, pg_data 0x18
E
E Apr 21 10:25:39.356657 str-7260cx3-acs-7 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_REMOVE failed in syncd mode: SAI_STATUS_OBJECT_IN_USE
E
E Apr 21 10:25:39.357022 str-7260cx3-acs-7 ERR swss#orchagent: :- remove: remove status: SAI_STATUS_OBJECT_IN_USE
E
E Apr 21 10:25:39.357022 str-7260cx3-acs-7 ERR swss#orchagent: :- processBufferProfile: Failed to remove buffer profile pg_lossless_40000_300m_profile with type BUFFER_PROFILE_TABLE, rv:-17
E
E Apr 21 10:25:39.357022 str-7260cx3-acs-7 ERR swss#orchagent: :- handleSaiRemoveStatus: Encountered failure in remove operation, exiting orchagent, SAI API: SAI_API_BUFFER, status: SAI_STATUS_OBJECT_IN_USE
```

2.	Error log 2 for test_update_description on latest 202205 image.
```
E               Match Messages:
E               Apr 21 10:27:42.741349 str-7260cx3-acs-7 ERR swss#supervisor-proc-exit-listener: Process 'orchagent' is not running in namespace 'host' (2.0 minutes)
```

3.	test_eth_interface_admin_change[down] case failed on latest 202205 image.
```
> pytest_assert(admin_status == running_status, "Interface failed to update admin status to {}".format(admin_status)) 
E Failed: Interface failed to update admin status to down 
```

4. For generic_config_updater.test_eth_interface.test_update_speed on master image:
```
failed on teardown with "Failed: Processes "['analyze_logs--<MultiAsicSonicHost str2-7050cx3-acs-06>']" failed with exit code "1"
Exception:
match: 3
expected_match: 0
expected_missing_match: 0

Match Messages:
Apr 21 17:28:31.137058 str2-7050cx3-acs-06 ERR sonic_yang: All Keys are not parsed in PORT#012dict_keys(['Ethernet0'])

Apr 21 17:28:31.137149 str2-7050cx3-acs-06 ERR sonic_yang: exceptionList:["invalid literal for int() with base 10: '20a'"]

Apr 21 17:28:31.137232 str2-7050cx3-acs-06 ERR sonic_yang: Data Loading Failed:All Keys are not parsed in PORT#012dict_keys(['Ethernet0'])#012exceptionList:["invalid literal for int() with base 10: '20a'"]

Traceback:
Traceback (most recent call last):
  File "/azp/_work/18/s/tests/common/helpers/parallel.py", line 35, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/azp/_work/18/s/tests/common/helpers/parallel.py", line 245, in wrapper
    target(*args, **
```

**Steps to reproduce the issue:**
1. Run generic_config_updater/test_eth_interface.py against master/internal/202205 image.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by isabelmsft** [comment]
Issue closed with this PR: https://github.com/sonic-net/sonic-utilities/pull/2936
