### ISSUE TITLE
Mentioned cases fails due to Ansible module failure in T0 physical topology.

### ISSUE THREAD

**Issue by Vickyni2** [sonic-net/sonic-mgmt#8382]
**Description**

The Below mentioned all the test cases got "Ansible module failure" .

**Failed Cases**
1.lldp/test_lldp.py
2.iface_namingmode/test_iface_namingmode.py
3.pc/test_lag_2.py
4.platform_tests/test_reboot.py
5.platform_tests/test_reload_config.py
6.snmp/test_snmp_psu.py
7.mvrf/test_mgmtvrf.py

**Describe the results you received:**

I have updated one case error snippet , all the cases got failed in same error. is this environmental issue or any specific code related issue .
 
        if (res.is_failed or 'exception' in res) and not module_ignore_errors:
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           RunAnsibleModuleFail: run module lldp_facts failed, Ansible Results =>
E           {"changed": false, "failed": true, "msg": "No SNMP response received before timeout"}

complex_args = {'community': 'strcommunity', 'host': '10.250.0.3', 'version': 'v2c'}
filename   = '/data/sonic-mgmt/tests/lldp/test_lldp.py'
function_name = 'test_lldp_neighbor'
index      = 0
line_number = 84
lines      = ["            host=hostip, version='v2c', community=eos['snmp_rocommunity'])['ansible_facts']\n"]
module_args = []
module_async = False
module_ignore_errors = False
previous_frame = <frame object at 0x7f311800f2d0>
res        = {u'invocation': {u'module_args': {u'username': None, u'privacy': None, u'level... '_ansible_no_log': False, u'msg': u'No SNMP response received before timeout'}
self       = <tests.common.devices.local.Localhost object at 0x7f31287dca50>
verbose    = True

common/devices/base.py:127: RunAnsibleModuleFail
- generated xml file: /data/sonic-mgmt/tests/logs/15-05-2023/test_lldp/tr.xml --
---------------------------- live log sessionfinish ----------------------------
10:32:58 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
=========================== short test summary info ============================
ERROR lldp/test_lldp.py::test_lldp[dev-msn2700-01-None] - Failed: Processes "...
ERROR lldp/test_lldp.py::test_lldp_neighbor[dev-msn2700-01-None] - Failed: Pr...
FAILED lldp/test_lldp.py::test_lldp[dev-msn2700-01-None] - KeyError: 'ifname'
FAILED lldp/test_lldp.py::test_lldp_neighbor[dev-msn2700-01-None] - RunAnsibl...
===================== 2 failed, 2 error in 250.59 seconds ======================

**Describe the results you expected:**
All the test cases should pass .

**Additional information you deem important:**

    **Output of `show version`:**

  SONiC Software Version: SONiC.202211.269499-59c7d39ef
SONiC OS Version: 11
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 59c7d39ef
Build date: Tue May 9 17:58:15 UTC 2023
Built by: AzDevOps@vmss-soni00118K
Platform: x86_64-accton_as7716_32x-r0
HwSKU: Accton-AS7716-32X
ASIC: broadcom
ASIC Count: 1

    **Attach debug file `sudo generate_dump`:**

**Comment by MahendranPackiam** [comment]
@yxieca @wangxin  Could you please check and support on this PR. Thanks

**Comment by wangxin** [comment]
@MahendranPackiam RunAnsibleModuleFail is a generic exception raised when running any ansible module failed on a host. Need to check the detailed error message and trace stack to find out more information of what ansible module failed with what arguments.

**Comment by mithun2498** [comment]
Hi @wangxin 

I have attached the case logs for your reference. 

[test_lldp1.txt](https://github.com/sonic-net/sonic-mgmt/files/12494356/test_lldp1.txt)
[test_snmp_psu_t0.txt](https://github.com/sonic-net/sonic-mgmt/files/12494357/test_snmp_psu_t0.txt)

**Comment by Krishnapriyanka-R** [comment]
Hi @wangxin

I have tried executing this vxlan_decap testcase in t0- vs but this case is also getting failed due to Ansible module failure the log and error is attached and mentioned below for your reference,
[test_vxlan_decap_t0.txt](https://github.com/sonic-net/sonic-mgmt/files/12697725/test_vxlan_decap_t0.txt)

```
06:00:06 test_vxlan_decap.test_vxlan_decap        L0177 INFO   | vxlan_enabled=True, scenario=Enabled
06:00:58 ptf_runner.ptf_runner                    L0102 ERROR  | Exception caught while executing case: vxlan-decap.Vxlan. Error message: Traceback (most recent call last):
  File "/data/sonic-mgmt/tests/ptf_runner.py", line 89, in ptf_runner
    result = host.shell(cmd, chdir="/root", module_ignore_errors=module_ignore_errors)
  File "/data/sonic-mgmt/tests/common/devices/base.py", line 127, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
```
 
 Thanks.
