### ISSUE TITLE
warm reboot and fast reboot test case failed on master image

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#9201]
**Description**
warn reboot case failed:

```
Traceback (most recent call last):
  File "/azp/_work/12/s/tests/common/fixtures/advanced_reboot.py", line 579, in runRebootTest
    thread.join(timeout=10)
  File "/azp/_work/12/s/tests/common/utilities.py", line 216, in join
    six.reraise(*self._e)
  File "/var/AzDevOps/env-python3/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/azp/_work/12/s/tests/common/utilities.py", line 194, in run
    threading.Thread.run(self)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/azp/_work/12/s/tests/common/fixtures/advanced_reboot.py", line 753, in __runPtfRunner
    result = ptf_runner(
  File "/azp/_work/12/s/tests/ptf_runner.py", line 89, in ptf_runner
    result = host.shell(cmd, chdir="/root", module_ignore_errors=module_ignore_errors)
  File "/azp/_work/12/s/tests/common/devices/base.py", line 127, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "ptf --test-dir ptftests advanced-reboot.ReloadTest --platform-dir ptftests --qlen=1000 --platform remote -t 'dut_username='\"'\"'admin'\"'\"';dut_password='\"'\"'password'\"'\"';dut_hostname='\"'\"'10.3.146.187'\"'\"';reboot_limit_in_seconds=0;reboot_type='\"'\"'warm-reboot'\"'\"';other_vendor_flag=False;portchannel_ports_file='\"'\"'/tmp/portchannel_interfaces.json'\"'\"';vlan_ports_file='\"'\"'/tmp/vlan_interfaces.json'\"'\"';ports_file='\"'\"'/tmp/ports.json'\"'\"';dut_mac='\"'\"'94:8e:d3:99:57:b8'\"'\"';vlan_mac='\"'\"'94:8e:d3:99:57:b8'\"'\"';lo_prefix='\"'\"'10.1.0.32/32'\"'\"';default_ip_range='\"'\"'192.168.64.0/18'\"'\"';vlan_ip_range='\"'\"'{\"Vlan1000\": \"192.168.0.0/21\"}'\"'\"';lo_v6_prefix='\"'\"'fc00:1::/64'\"'\"';arista_vms=['\"'\"'172.16.137.119'\"'\"', '\"'\"'172.16.137.118'\"'\"', '\"'\"'172.16.137.117'\"'\"', '\"'\"'172.16.137.116'\"'\"'];nexthop_ips=None;allow_vlan_flooding=False;sniff_time_incr=300;setup_fdb_before_test=True;vnet=False;vnet_pkts='\"'\"''\"'\"';bgp_v4_v6_time_diff=40;asic_type='\"'\"'broadcom'\"'\"';allow_mac_jumping=False;preboot_files='\"'\"'peer_dev_info,neigh_port_info'\"'\"';alt_password='\"'\"'YourPaSsWoRd'\"'\"';service_list=None;service_data=None;neighbor_type='\"'\"'eos'\"'\"';preboot_oper=None;inboot_oper=None' --relax --debug info --log-file /tmp/advanced-reboot.ReloadTest.log --test-case-timeout 2100", "delta": "0:05:11.764768", "end": "2023-07-29 07:11:56.377592", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-07-29 07:06:44.612824", "stderr": "WARNING: No route found for IPv6 destination :: (no default route?)\n/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.hazmat.backends import default_backend\nadvanced-reboot.ReloadTest ... FAIL\n\n======================================================================\nFAIL: advanced-reboot.ReloadTest\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"ptftests/advanced-reboot.py\", line 1402, in runTest\n    self.handle_post_reboot_test_reports()\n  File \"ptftests/advanced-reboot.py\", line 1338, in handle_post_reboot_test_reports\n    self.assertTrue(is_good, errors)\nAssertionError: \n\nSomething went wrong. Please check output below:\n\nFAILED:dut:Traceback (most recent call last):\n  File \"ptftests/advanced-reboot.py\", line 1345, in runTest\n    self.wait_dut_to_warm_up()\n  File \"ptftests/advanced-reboot.py\", line 2129, in wait_dut_to_warm_up\n    ctrlplane, dataplane))\nException: IO didn't come up within warm up timeout. Control plane: up, Data plane: down\n\nFAILED:dut:DUT is not ready for test\n\n\n----------------------------------------------------------------------\nRan 1 test in 310.008s\n\nFAILED (failures=1)", "stderr_lines": ["WARNING: No route found for IPv6 destination :: (no default route?)", "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.", "  from cryptography.hazmat.backends import default_backend", "advanced-reboot.ReloadTest ... FAIL", "", "======================================================================", "FAIL: advanced-reboot.ReloadTest", "----------------------------------------------------------------------", "Traceback (most recent call last):", "  File \"ptftests/advanced-reboot.py\", line 1402, in runTest", "    self.handle_post_reboot_test_reports()", "  File \"ptftests/advanced-reboot.py\", line 1338, in handle_post_reboot_test_reports", "    self.assertTrue(is_good, errors)", "AssertionError: ", "", "Something went wrong. Please check output below:", "", "FAILED:dut:Traceback (most recent call last):", "  File \"ptftests/advanced-reboot.py\", line 1345, in runTest", "    self.wait_dut_to_warm_up()", "  File \"ptftests/advanced-reboot.py\", line 2129, in wait_dut_to_warm_up", "    ctrlplane, dataplane))", "Exception: IO didn't come up within warm up timeout. Control plane: up, Data plane: down", "", "FAILED:dut:DUT is not ready for test", "", "", "----------------------------------------------------------------------", "Ran 1 test in 310.008s", "", "FAILED (failures=1)"], "stdout": "2023-07-29 07:06:46 : Converted addresses VMs: ['172.16.137.119', '172.16.137.118', '172.16.137.117', '172.16.137.116']\n2023-07-29 07:06:46 : Test params:\n2023-07-29 07:06:46 : DUT ssh: admin@10.3.146.187\n2023-07-29 07:06:46 : DUT reboot limit in seconds: 0:00:00\n2023-07-29 07:06:46 : DUT mac address: 94:8e:d3:99:57:b8\n2023-07-29 07:06:46 : DUT vlan mac address: 94:8e:d3:99:57:b8\n2023-07-29 07:06:46 : From server src addr: 192.168.0.177\n2023-07-29 07:06:46 : From server src port: 10\n2023-07-29 07:06:46 : From server dst addr: 192.168.79.54\n2023-07-29 07:06:46 : From server dst ports: [31, 28, 30, 29]\n2023-07-29 07:06:46 : From upper layer number of packets: 500\n2023-07-29 07:06:46 : VMs: ['172.16.137.119', '172.16.137.118', '172.16.137.117', '172.16.137.116']\n2023-07-29 07:06:46 : Reboot type is warm-reboot\n2023-07-29 07:06:47 : ARP ping: src idx 18 port 19 mac 72:06:00:01:00:16 addr 192.168.0.18\n2023-07-29 07:06:47 : ARP ping: dst idx 2 port 3 addr 192.168.0.2\n2023-07-29 07:06:47 : \n2023-07-29 07:06:47 : Enabling arp_responder\n2023-07-29 07:06:48 : SSH thread for VM 172.16.137.119 started\n2023-07-29 07:06:48 : SSH thread for VM 172.16.137.118 started\n2023-07-29 07:06:48 : SSH thread for VM 172.16.137.117 started\n2023-07-29 07:06:48 : Run some server traffic to populate FDB table...\n2023-07-29 07:06:48 : SSH thread for VM 172.16.137.116 started\n2023-07-29 07:06:49 : Starting reachability state watch thread...\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.118: show lacp command is 'show lacp peer'\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.119: show lacp command is 'show lacp peer'\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.116: show lacp command is 'show lacp peer'\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.117: show lacp command is 'show lacp peer'\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.116: show ip bgp neighbor command is 'show ip bgp neighbors'\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.118: show ip bgp neighbor command is 'show ip bgp neighbors'\n2023-07-29 07:06:50 : SSH thread VM=172.16.137.119: show ip bgp neighbor command is 'show ip bgp neighbors'\n2023-07-29 07:06:51 : SSH thread VM=172.16.137.117: show ip bgp neighbor command is 'show ip bgp neighbors'\n2023-07-29 07:06:51 : SSH thread VM=172.16.137.116: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'\n2023-07-29 07:06:51 : SSH thread VM=172.16.137.118: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'\n2023-07-29 07:06:51 : SSH thread VM=172.16.137.119: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'\n2023-07-29 07:06:51 : SSH thread VM=172.16.137.117: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'\n2023-07-29 07:06:54 : Check that device is alive and pinging\n2023-07-29 07:06:55 : Data plane state transition from init to down (47)\n2023-07-29 07:06:56 : Control plane state transition from init to down\n2023-07-29 07:06:57 : VLAN ARP state transition from init to down\n2023-07-29 07:07:42 : Control plane state transition from down to partial\n2023-07-29 07:07:44 : VLAN ARP state transition from down to up\n2023-07-29 07:07:47 : Control plane state transition from partial to up\n2023-07-29 07:11:54 : ==================================================\n2023-07-29 07:11:54 : Report:\n2023-07-29 07:11:54 : ==================================================\n2023-07-29 07:11:54 : LACP/BGP were down for (extracted from cli):\n2023-07-29 07:11:54 : --------------------------------------------------\n2023-07-29 07:11:54 : --------------------------------------------------\n2023-07-29 07:11:54 : Extracted from VM logs:\n2023-07-29 07:11:54 : --------------------------------------------------\n2023-07-29 07:11:54 : Summary:\n2023-07-29 07:11:54 : --------------------------------------------------\n2023-07-29 07:11:54 : --------------------------------------------------\n2023-07-29 07:11:54 : Fails:\n2023-07-29 07:11:54 : --------------------------------------------------\n2023-07-29 07:11:54 : FAILED:dut:Traceback (most recent call last):\n  File \"ptftests/advanced-reboot.py\", line 1345, in runTest\n    self.wait_dut_to_warm_up()\n  File \"ptft", "stdout_lines": ["2023-07-29 07:06:46 : Converted addresses VMs: ['172.16.137.119', '172.16.137.118', '172.16.137.117', '172.16.137.116']", "2023-07-29 07:06:46 : Test params:", "2023-07-29 07:06:46 : DUT ssh: admin@10.3.146.187", "2023-07-29 07:06:46 : DUT reboot limit in seconds: 0:00:00", "2023-07-29 07:06:46 : DUT mac address: 94:8e:d3:99:57:b8", "2023-07-29 07:06:46 : DUT vlan mac address: 94:8e:d3:99:57:b8", "2023-07-29 07:06:46 : From server src addr: 192.168.0.177", "2023-07-29 07:06:46 : From server src port: 10", "2023-07-29 07:06:46 : From server dst addr: 192.168.79.54", "2023-07-29 07:06:46 : From server dst ports: [31, 28, 30, 29]", "2023-07-29 07:06:46 : From upper layer number of packets: 500", "2023-07-29 07:06:46 : VMs: ['172.16.137.119', '172.16.137.118', '172.16.137.117', '172.16.137.116']", "2023-07-29 07:06:46 : Reboot type is warm-reboot", "2023-07-29 07:06:47 : ARP ping: src idx 18 port 19 mac 72:06:00:01:00:16 addr 192.168.0.18", "2023-07-29 07:06:47 : ARP ping: dst idx 2 port 3 addr 192.168.0.2", "2023-07-29 07:06:47 : ", "2023-07-29 07:06:47 : Enabling arp_responder", "2023-07-29 07:06:48 : SSH thread for VM 172.16.137.119 started", "2023-07-29 07:06:48 : SSH thread for VM 172.16.137.118 started", "2023-07-29 07:06:48 : SSH thread for VM 172.16.137.117 started", "2023-07-29 07:06:48 : Run some server traffic to populate FDB table...", "2023-07-29 07:06:48 : SSH thread for VM 172.16.137.116 started", "2023-07-29 07:06:49 : Starting reachability state watch thread...", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.118: show lacp command is 'show lacp peer'", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.119: show lacp command is 'show lacp peer'", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.116: show lacp command is 'show lacp peer'", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.117: show lacp command is 'show lacp peer'", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.116: show ip bgp neighbor command is 'show ip bgp neighbors'", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.118: show ip bgp neighbor command is 'show ip bgp neighbors'", "2023-07-29 07:06:50 : SSH thread VM=172.16.137.119: show ip bgp neighbor command is 'show ip bgp neighbors'", "2023-07-29 07:06:51 : SSH thread VM=172.16.137.117: show ip bgp neighbor command is 'show ip bgp neighbors'", "2023-07-29 07:06:51 : SSH thread VM=172.16.137.116: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'", "2023-07-29 07:06:51 : SSH thread VM=172.16.137.118: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'", "2023-07-29 07:06:51 : SSH thread VM=172.16.137.119: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'", "2023-07-29 07:06:51 : SSH thread VM=172.16.137.117: show ipv6 bgp neighbor command is 'show ipv6 bgp peers'", "2023-07-29 07:06:54 : Check that device is alive and pinging", "2023-07-29 07:06:55 : Data plane state transition from init to down (47)", "2023-07-29 07:06:56 : Control plane state transition from init to down", "2023-07-29 07:06:57 : VLAN ARP state transition from init to down", "2023-07-29 07:07:42 : Control plane state transition from down to partial", "2023-07-29 07:07:44 : VLAN ARP state transition from down to up", "2023-07-29 07:07:47 : Control plane state transition from partial to up", "2023-07-29 07:11:54 : ==================================================", "2023-07-29 07:11:54 : Report:", "2023-07-29 07:11:54 : ==================================================", "2023-07-29 07:11:54 : LACP/BGP were down for (extracted from cli):", "2023-07-29 07:11:54 : --------------------------------------------------", "2023-07-29 07:11:54 : --------------------------------------------------", "2023-07-29 07:11:54 : Extracted from VM logs:", "2023-07-29 07:11:54 : --------------------------------------------------", "2023-07-29 07:11:54 : Summary:", "2023-07-29 07:11:54 : --------------------------------------------------", "2023-07-29 07:11:54 : --------------------------------------------------", "2023-07-29 07:11:54 : Fails:", "2023-07-29 07:11:54 : --------------------------------------------------", "2023-07-29 07:11:54 : FAILED:dut:Traceback (most recent call last):", "  File \"ptftests/advanced-reboot.py\", line 1345, in runTest", "    self.wait_dut_to_warm_up()", "  File \"ptft"]}
```

Both warm reboot and fast reboot cases failed at teardown:

```
>       pytest_assert(check_all, "Health check failed after reboot: {}"
                      .format(test_report))
E       Failed: Health check failed after reboot: {'check_services': True, 'check_interfaces_and_transceivers': "Interface check failed, not all interfaces are up. Failed: [{'failed': True, 'check_item': 'interfaces', 'host': 'str2-7050cx3-acs-02', 'down_ports': ['Ethernet112', 'Ethernet116', 'Ethernet12', 'Ethernet120', 'Ethernet124', 'Ethernet16', 'Ethernet20', 'Ethernet24', 'Ethernet28', 'Ethernet32', 'Ethernet36', 'Ethernet4', 'Ethernet40', 'Ethernet44', 'Ethernet48', 'Ethernet52', 'Ethernet56', 'Ethernet60', 'Ethernet64', 'Ethernet68', 'Ethernet72', 'Ethernet76', 'Ethernet8', 'Ethernet80', 'Ethernet84', 'Ethernet88', 'Ethernet92', 'Ethernet96']}]", 'check_neighbors': True, 'verify_no_coredumps': True}
```

**Steps to reproduce the issue:**
1. Load master image
2. Run tests/platform_tests/test_advanced_reboot.py
3.
4.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vaibhavhd** [comment]
The failure seems to be in dataplane warmup path. Device was dropping traffic even before warm-reboot.

`Exception: IO didn't come up within warm up timeout. Control plane: up, Data plane: down\n\nFAILED:dut:DUT is not ready for test\n`

Also it looks like all interfaces are down? 
`"Interface check failed, not all interfaces are up. Failed: [{'failed': True, 'check_item': 'interfaces', 'host': 'str2-7050cx3-acs-02', 'down_ports': ['Ethernet112', 'Ethernet116', 'Ethernet12', 'Ethernet120', 'Ethernet124', 'Ethernet16', 'Ethernet20', 'Ethernet24', 'Ethernet28', 'Ethernet32', 'Ethernet36', 'Ethernet4', 'Ethernet40', 'Ethernet44', 'Ethernet48', 'Ethernet52', 'Ethernet56', 'Ethernet60', 'Ethernet64', 'Ethernet68', 'Ethernet72', 'Ethernet76', 'Ethernet8', 'Ethernet80', 'Ethernet84', 'Ethernet88', 'Ethernet92', 'Ethernet96']}]`

**Comment by vaibhavhd** [comment]
@ZhaohuiS are there more logs for this? This looks like a testbed health issue to me.

**Comment by ZhaohuiS** [comment]
@vaibhavhd https://dev.azure.com/mssonic/internal/_build/results?buildId=325963&view=logs&j=bed026c5-b179-58e8-339f-77f4b7309744&t=3d56b420-5b0a-59fb-e15f-64a2477dcafc
This is the pipeline log, happened on 7050cx3 platform.


This is log file:
[test_advanced_reboot.log](https://github.com/sonic-net/sonic-mgmt/files/12449518/test_advanced_reboot.log)


This case is xfailed right now.
