### ISSUE TITLE
sonic-mgmt docker image should have all the necessary libraries installed

### ISSUE THREAD

**Issue by harshsikhwal** [sonic-net/sonic-mgmt#9484]
**Description**

The sonic-mgmt docker image does not contains python env in the /root/ directory by default and requires additional steps as mentioned in the setup_container.sh (https://github.com/sonic-net/sonic-mgmt/blob/520d32aa3b69338688aeec800f2972ca2d14725f/setup-container.sh#L245) for tests to run. By default this image, if downloaded directly has python env set in _/var/AzDevOps/env-python3_ but most tests are dependent on ptf and they look for the python env in _/root/env-python3_. The setup_container.sh is an additional step needed to be done  which sets the new python path and copies the existing python pip dependencies. The image should by default have all the necessary dependencies pre-installed rather than done by the user. 

The setup_container workflow leads to another issue as some of the python packages may not exist and throw errors when trying to create the environment. This is another major problem.

![image](https://github.com/sonic-net/sonic-mgmt/assets/52648233/109e1e3b-07ca-46b7-97e2-2964cff78b57)

**Steps to reproduce the issue:**
1. Pull the sonic-mgmt image from sonicdev-microsoft.azurecr.io:443/docker-sonic-mgmt:latest
2. Run this image directly using docker run 
3. Try running dhcp_relay/test_dhcpv6_relay.py or any test that is dependent on tests/ptf_runner.py (https://github.com/sonic-net/sonic-mgmt/blob/520d32aa3b69338688aeec800f2972ca2d14725f/tests/ptf_runner.py#L37)

**Describe the results you received:**
The tests fails as ptf module is not found in /root/env-python3

Output:

_16:24:06 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/sonic-mgmt/custom_tests/dhcp_relay/test_dhcpv6_relay.py", line 250, in test_dhcp_relay_default
    log_file="/tmp/dhcpv6_relay_test.DHCPTest.log", is_python3=True)
  File "/data/sonic-mgmt/tests/ptf_runner.py", line 44, in ptf_runner
    raise Exception(error_msg)
Exception: Virtual environment for Python3 /root/env-python3/bin/ptf doesn't exist.
Please check and update docker-ptf image, make sure to use the correct one._

**Describe the results you expected:**

The tests should run well without manual changes or running setup_container.sh

**Comment by nikunjdh** [comment]
Hi,

Recently, on running setup-container.sh on Ubuntu 20.4 VM to bring up KVM based topology, I am seeing following error:

#0 27.39 ERROR: Could not find a version that satisfies the requirement distro-info==0.23+ubuntu1.1 (from versions: 0.10, 1.0)
#0 27.39 ERROR: No matching distribution found for distro-info==0.23+ubuntu1.1

Is there any option to resolve this error?  Earlier, on same VM, no error was seen. Does this has something do with latest sonic-mgmt image?

**Comment by harshsikhwal** [comment]
Hi @nikunjdh 

I think the version for the python library distro-info does not exist. I think the sonic-mgmt docker was using this version and now this does not exist. 

Maybe you need to handcraft the build, like get all the packages, and then iterate and install; skip which does not exist or throw error and install the latest version?

**Comment by nikunjdh** [comment]
Hi @harshsikhwal 

Seem like latest sonic-mgmt docker image is looking for distro-info==0.23+ubuntu1.1 now and it does not exist.  distro-info version 0.23+ubuntu1.1 is recently released - Aug 3rd 2023. 

Error is seen while setup-container.sh is running following command:

RUN if [ 'cisco' != 'AzDevOps' ] && [ -d /var/AzDevOps/env-python3 ]; then /bin/bash -c 'python3 -m venv ${HOME}/env-python3'; /bin/bash -c '${HOME}/env-python3/bin/pip install pip --upgrade'; /bin/bash -c '${HOME}/env-python3/bin/pip install wheel'; /bin/bash -c '${HOME}/env-python3/bin/pip install $(/var/AzDevOps/env-python3/bin/pip freeze)'; fi: 

So, I would expect it to install all required packages/version including distro-info==0.23+ubuntu1.1

**Comment by harshsikhwal** [comment]
Can you try doing a pip install normally for the same package?

I see the following issue: 
![image](https://github.com/sonic-net/sonic-mgmt/assets/52648233/8061dbbc-3202-4b8d-ba42-1dbcb32da6c1)

Not sure if the python package exist for the same version.

**Comment by nikunjdh** [comment]
Here is what, I see on my VM:
sudo pip3 show distro-info
Name: distro-info
Version: 0.23ubuntu1
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 

~$ sudo pip3 install distro-info==0.23ubuntu1.0
Requirement already satisfied: distro-info==0.23ubuntu1.0 in /usr/lib/python3/dist-packages (0.23ubuntu1)
~$ sudo pip3 install distro-info==0.23ubuntu1.1
ERROR: Could not find a version that satisfies the requirement distro-info==0.23ubuntu1.1 (from versions: 0.10, 1.0)
ERROR: No matching distribution found for distro-info==0.23ubuntu1.1

~$ sudo pip3 install distro-info==0.23+ubuntu1.1
ERROR: Could not find a version that satisfies the requirement distro-info==0.23+ubuntu1.1 (from versions: 0.10, 1.0)
ERROR: No matching distribution found for distro-info==0.23+ubuntu1.1

I can see package with version 0.23ubuntu1.1 at https://launchpad.net/ubuntu/+source/distro-info/0.23ubuntu1.1

It's not clear why setup-container.sh is trying to install this version all of sudden.

**Comment by yxieca** [comment]
@wangxin can you triage this issue?

The immediate issue was addressed by #9440.

Can you assess the suggestion of sonic-mgmt docker being self-sufficient?

**Comment by mrkcmo** [comment]
We are running into this issues as well getting error when running the setup-container:

```
30.64   Downloading distro-1.4.0-py2.py3-none-any.whl (17 kB)
30.71 ERROR: Ignored the following versions that require a different python version: 7.0.0 Requires-Python >=3.9; 7.0.0a1 Requires-Python >=3.9.0; 7.0.0a2 Requires-Python >=3.9; 7.0.0b1 Requires-Python >=3.9; 7.0.0rc1 Requires-Python >=3.9; 7.1.0 Requires-Python >=3.9; 7.2.0 Requires-Python >=3.9; 7.3.0 Requires-Python >=3.9; 7.4.0 Requires-Python >=3.9; 7.5.0 Requires-Python >=3.9; 7.6.0 Requires-Python >=3.9; 7.7.0 Requires-Python >=3.9; 8.0.0 Requires-Python >=3.9; 8.0.0a1 Requires-Python >=3.9; 8.0.0a2 Requires-Python >=3.9; 8.0.0a3 Requires-Python >=3.9; 8.0.0b1 Requires-Python >=3.9; 8.0.0rc1 Requires-Python >=3.9; 8.1.0 Requires-Python >=3.9; 8.2.0 Requires-Python >=3.9; 8.3.0 Requires-Python >=3.9; 8.4.0 Requires-Python >=3.9
30.71 ERROR: Could not find a version that satisfies the requirement distro-info==0.23+ubuntu1.1 (from versions: 0.10, 1.0)
30.71 ERROR: No matching distribution found for distro-info==0.23+ubuntu1.1
------
Dockerfile:61
--------------------
  60 |     # Setup python3 virtual env
  61 | >>> RUN if [ 'cisco' != 'AzDevOps' ] && [ -d /var/AzDevOps/env-python3 ]; then \
  62 | >>> /bin/bash -c 'python3 -m venv ${HOME}/env-python3'; \
  63 | >>> /bin/bash -c '${HOME}/env-python3/bin/pip install pip --upgrade'; \
  64 | >>> /bin/bash -c '${HOME}/env-python3/bin/pip install wheel'; \
  65 | >>> /bin/bash -c '${HOME}/env-python3/bin/pip install $(/var/AzDevOps/env-python3/bin/pip freeze)'; \
  66 | >>> fi
  67 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ 'cisco' != 'AzDevOps' ] && [ -d /var/AzDevOps/env-python3 ]; then /bin/bash -c 'python3 -m venv ${HOME}/env-python3'; /bin/bash -c '${HOME}/env-python3/bin/pip install pip --upgrade'; /bin/bash -c '${HOME}/env-python3/bin/pip install wheel'; /bin/bash -c '${HOME}/env-python3/bin/pip install $(/var/AzDevOps/env-python3/bin/pip freeze)'; fi" did not complete successfully: exit code: 1
ERROR: failed to build docker image: docker-sonic-mgmt-cisco:master
INFO: cleanup a temporary dir: /tmp/tmp.PwV9KIKHrC

ERROR: failed to build docker image: docker-sonic-mgmt-cisco:master
```
Looks like this might be related to a setup-tools issue that has been identified here: https://stackoverflow.com/questions/75272737/error-invalid-version-0-23ubuntu1-package-distro-info

@wangxin  thoughts?
