### ISSUE TITLE
test_lag_member.py doesn't work  on branch 202205, but it work on branch master

### ISSUE THREAD

**Issue by JibinBao** [sonic-net/sonic-mgmt#9964]
**Description**
test_lag_member.py doesn't work  on branch 202205, but it work on branch master.
On branch 202205, it seems missing some commit, maybe it need to cherry-pick some commit from develop branch.

**Steps to reproduce the issue:**
1. Run test_lag_member.py

**Describe the results you received:**

```
@pytest.fixture(scope="module")
    def ptf_dut_setup_and_teardown(duthost, ptfhost, tbinfo):
        """
        Setup and teardown of ptf and dut
    
        Args:
            duthost: DUT host object
            ptfhost: PTF host object
            tbinfo: fixture provides information about testbed
        """
        dut_ports, ptf_ports, src_vlan_id, vlan = generate_port_config(duthost, tbinfo)
        try:
            setup_dut_lag(duthost, dut_ports, vlan, src_vlan_id)
            setup_ptf_lag(ptfhost, ptf_ports)
    
            yield dut_ports, ptf_ports, vlan
        except Exception as err:
            pytest.fail("Setup failed with error: {}".format(err))
        finally:
            dut_teardown(duthost, dut_ports, src_vlan_id, vlan)
>           ptf_teardown(ptfhost, ptf_ports)

dut_ports  = {'port_behind_lag': {25: 'Ethernet50', 26: 'Ethernet52', 29: 'Ethernet58', 48: 'Ethernet96', ...}, 'port_not_behind_lag': {'port_id': 39, 'port_name': 'Ethernet78'}}
err        = run module shell failed, Ansible Results =>
{"changed": true, "cmd": "config p...er members of the portchannel PortChannel1"], "stdout": "", "stdout_lines": []}
ptf_ports  = {'ip': {'lag': '192.168.9.2/24', 'port_not_behind_lag': '192.168.9.3/24'}, 'port_behind_lag': {25: 'eth25', 26: 'eth26', 29: 'eth29', 48: 'eth48', ...}, 'port_not_behind_lag': {'port_id': 39, 'port_name': 'eth39'}}
ptfhost    = <tests.common.devices.ptf.PTFHost object at 0x7f20803bca10>
src_vlan_id = 1000



{"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": true, "cmd": ["ip", "link", "set", "bond1", "nomaster"], "delta": "0:00:00.457790", "end": "2023-09-09 01:37:53.622403", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-09-09 01:37:53.164613", "stderr": "Cannot find device \"bond1\"", "stderr_lines": ["Cannot find device \"bond1\""], "stdout": "", "stdout_lines": []}
Traceback (most recent call last):
  File "/root/mars/workspace/sonic-mgmt/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "/root/mars/workspace/sonic-mgmt/tests/pc/test_lag_member.py", line 321, in ptf_dut_setup_and_teardown
    ptf_teardown(ptfhost, ptf_ports)
  File "/root/mars/workspace/sonic-mgmt/tests/pc/test_lag_member.py", line 111, in ptf_teardown
    ptfhost.set_dev_no_master(PTF_LAG_NAME)
  File "/root/mars/workspace/sonic-mgmt/tests/common/devices/ptf.py", line 109, in set_dev_no_master
    self.command("ip link set {} nomaster".format(dev_name))
  File "/root/mars/workspace/sonic-mgmt/tests/common/devices/base.py", line 90, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
RunAnsibleModuleFail: run module command failed, Ansible Results =>
{"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": true, "cmd": ["ip", "link", "set", "bond1", "nomaster"], "delta": "0:00:00.457790", "end": "2023-09-09 01:37:53.622403", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-09-09 01:37:53.164613", "stderr": "Cannot find device \"bond1\"", "stderr_lines": ["Cannot find device \"bond1\""], "stdout": "", "stdout_lines": []}
```

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
From the backtrace, the error is because command ```ip link set bond1 nomaster``` returns error ```Cannot find device "bond1"```
The bond1 should be created on ptf during the test setup. Can you check if the setup failed as well?

**Comment by JibinBao** [comment]
will check it
